### PR TITLE
Fix: Timeseries aligned center in homepage for mobile devices

### LINKED ISSUE #1807: Timeseries explorer not aligned center in homepage in mobile
**Describe the bug**
Timeseries explorer elements are not aligned center. They are towards left side.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Home
2. Scroll down to timeseries explorer
3. Notice the issue

**Expected behavior**
It should be same as in state page

**Screenshots**
 
Screenshot_20200506-171915

### PR DESCRIPTION
**Pull request by nayakrahul**
**Description of PR**
Timeseries is aligned center in homepage for mobile devices by making css changes. Before it was towards left side.

**Relevant Issues**  
Fixes #1807 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
### before
Screenshot_20200507-173453

### after
Screenshot_20200507-173436

### CODE REVIEW

**Comment by shuklaayush** [comment]
Looks like this breaks the intersection observer. The charts aren't updating on hovering the states

**Comment by nayakrahul** [comment]
> Looks like this breaks the intersection observer. The charts aren't updating on hovering the states

@shuklaayush I solved the issue by following another approach, made css changes. It is not breaking the observer and also fixed the alignment issue.

**Comment by nayakrahul** [comment]
@shuklaayush @jeremyphilemon please review this. I have not made any changes in Insersection Observer (so no interference there), just set margins to make it center aligned.

**Comment by shuklaayush** [comment]
Hey @nayakrahul, sorry about the delay. This was because I put the intersection observer at the wrong place. Should be fixed with 7740f5c8f764b7a521fdfae695b622f160d2e734. Thanks for the PR anyway

**Pull request closed without merging**
