### PR TITLE
Style: New footer design

### PR DESCRIPTION
**Pull request by HarshSBhatt**
New layout of footer implemented

### CODE REVIEW

**Comment by Binu42** [comment]
@harshzalavadiya it's currently unresponsive in mobile devices. you can use below css to make it responsive. change few more things it's not looking good in mobile  view.
```css
 .footer-wrapper .footer-social a {
    border-radius: 5px;
    margin: 0 20px;
    margin-top: 20px;
}
```

```css
.footer-wrapper .footer-social {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    flex-direction: row;
}
```

**Comment by HarshSBhatt** [comment]
> ```css
>     border-radius: 5px;
>     margin: 0 20px;
>     margin-top: 20px;
> ```

The mentioned margins are not appropriate as I just tried and it breaks width, anyway I edited things please check it once it is done

**Comment by HarshSBhatt** [comment]
> @harshzalavadiya it's currently unresponsive in mobile devices. you can use below css to make it responsive. change few more things it's not looking good in mobile view.
> 
> ```css
>  .footer-wrapper .footer-social a {
>     border-radius: 5px;
>     margin: 0 20px;
>     margin-top: 20px;
> }
> ```
> 
> ```css
> .footer-wrapper .footer-social {
>     display: flex;
>     flex-wrap: wrap;
>     justify-content: center;
>     flex-direction: row;
> }
> ```

I think you may find a horizontal scroll in small screen (s5, iPhone X) but it is of chorolepleth component

**Comment by openaudiologist** [comment]
@HarshSBhatt tried this to improve the desktop view a bit. thought there was too much spacing. you can try once maybe. it's more close to the mockups.

.footer-obj {
    padding: 60px 0px;
}

.footer-wrapper .footer-social a {
    margin: 0 10px;
}

.footer-wrapper .footer-social a .tooltiptext {
    width: 200px;
    margin-left: -105px;
}

**Comment by HarshSBhatt** [comment]
> @HarshSBhatt tried this to improve the desktop view a bit. thought there was too much spacing. you can try once maybe. it's more close to the mockups.
> 
> .footer-obj {
> padding: 60px 0px;
> }
> 
> .footer-wrapper .footer-social a {
> margin: 0 10px;
> }
> 
> .footer-wrapper .footer-social a .tooltiptext {
> width: 200px;
> margin-left: -105px;
> }

Yeah, it is good, but -105 don't make it to centre, so it is better to be -100 if width is 200px
Please check new preview once it is ready :)

**Comment by pastelsky** [comment]
👋 was trying this out on mobile –and it wasn't intuitive where I had to click to open the link.
Folks don't usually expect tooltips to be clickable.

**Comment by HarshSBhatt** [comment]
>  was trying this out on mobile –and it wasn't intuitive where I had to click to open the link.
> Folks don't usually expect tooltips to be clickable.

I was asked to open link when user click on tooltip

**Comment by jeremyphilemon** [comment]
I agree with @pastelsky. Can we retain the current design and just have the new social media handles added? Thanks :)

**Comment by HarshSBhatt** [comment]
> I agree with @pastelsky. Can we retain the current design and just have the new social media handles added? Thanks :)

Hey! That is good!.. I updated that touch event, now it is opening link on icon click instead of tooltip on mobile. Still We can go with old design if you want. :)

**Review by MrOwaisYosuf — CHANGES_REQUESTED** [review]
Please check the map of Jammu and Kashmir. It's having problem in "bandipore" district as it is displaying 0 cases in map, which actually has 128 cases. And it's displaying yesterday's data wrong about state (Jammu and Kashmir). Yesterday's cases were 25, but it's showing only 10 in bar graph under "Top districts" catagory. Please check once and fix that bug.

**Comment by bee-rickey** [comment]
Closing this as the decision is to go with current design.

**Pull request closed without merging**
