### PR TITLE
Fix: Enhance sort logic (#285)

### LINKED ISSUE #285: Enhance sort logic
**Is your feature request related to a problem? Please describe.**
Enhance sort function to sort by changes and total affected. If some states have equal number of affected people, it should then sort them on `delta`. Whichever has higher delta will be shown on top. 
image

**Describe the solution you'd like**
Would like to update the sort function that I wrote in my pr #211 if it gets merged. 

In the screenshot attached, if the states have same number of patients, they are then sorted alphabetically - obviously. It'd be great if there were a one more level of sorting on delta.

### PR DESCRIPTION
**Pull request by Shivamohan07**

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
What's the strategy being used here to sort by deltas, I can't seem to reproduce any sorting at the moment?

**Comment by Shivamohan07** [comment]
> What's the strategy being used here to sort by deltas, I can't seem to reproduce any sorting at the moment?

Please try now, apologies for the miss. The idea is to sort the rows, based on sort column and on the delta value in case of a collision.

https://covid19india-react-hlmwjpcl0.now.sh/

**Comment by vramana** [comment]
@Shivamohan07 Can you rebase?

**Comment by Shivamohan07** [comment]
> @Shivamohan07 Can you rebase?

Fixed the conflicts.

**Comment by jeremyphilemon** [comment]
Closing this because this seems to be too meticulous. The simple sorting right now is enough, but if need I'll definitely revisit this PR! Closing for now, thanks :)

**Pull request closed without merging**
