### PR TITLE
Data is not shown properly.

### PR DESCRIPTION
**Pull request by SinghRajenM**
**Description of PR**
1. Recent change voids https://github.com/covid19india/covid19india-react/pull/320
2. Dholpur info is not shown on the map

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #320 again

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
## Now
image

## Then
image

### CODE REVIEW

**Comment by thahir007cp** [comment]
Please take care of this similar issue too https://github.com/covid19india/covid19india-react/issues/645

**Comment by jeremyphilemon** [comment]
@guneetnarula can you review this?

**Review by guneetnarula — COMMENTED** [review]
Let's keep it as Dhaulpur, it has been fixed via data validation

**Comment by SinghRajenM** [comment]
> 
> 
> Let's keep it as Dhaulpur, it has been fixed via data validation

Than what about chittorgarh and Sri Ganganagar? These are wrong..

FYI, "Dhaulpur" is wrong. Refer official Rajasthan site - https://rajasthan.gov.in/Government/DistrictGovernment/Pages/default.aspx

**Comment by guneetnarula** [comment]
> Than what about chittorgarh and Sri Ganganagar? These are wrong..
> 
> FYI, "Dhaulpur" is wrong. Refer official Rajasthan site - https://rajasthan.gov.in/Government/DistrictGovernment/Pages/default.aspx

Yes @SinghRajenM that's true. The names are inconsistent everywhere. We went with the district names used by the registrar general of india, and survey of india (see bharatmaps.gov.in for example)

I think the point is that the data should show correctly on the map, which we are solving by standardization and validation

**Pull request closed without merging**
