### PR TITLE
fixed modal fully

### PR DESCRIPTION
**Pull request by Binu42**
**Description of PR**
stopped scrolling of page when modal is open and close the modal from anywhere outside modal on click.
**Type of PR**

- [x] Bugfix
- [ ] New featur

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
##### Before
gify

<br>

##### After
After

### CODE REVIEW

**Comment by denvamsi** [comment]
Iam not sure, This is yet working :)

**Review by Binu42 — COMMENTED** [review]
fixed scrolling of body to top on modal open.

**Comment by Binu42** [comment]
@denvamsi  check it out once. it's working. if any issues mention it. we will solve it together.

**Comment by denvamsi** [comment]
> fixed scrolling of body to top on modal open.

Yes i understood, But currently it looks very ugly. Like you have used 100vh which covers all the viewport, Instead you can use this: 

.modal .modal-content {
    width: 30rem;
    height: 30rem;
    overflow-y: auto;
}

So it looks like this adapts whenever more content it shows scrollbar.

image

**Comment by denvamsi** [comment]
This gives the better look :)

**Comment by Binu42** [comment]
> > fixed scrolling of body to top on modal open.
> 
> Yes i understood, But currently it looks very ugly. Like you have used 100vh which covers all the viewport, Instead you can use this:
> 
> .modal .modal-content {
> width: 30rem;
> height: 30rem;
> overflow-y: auto;
> }
> 
> So it looks like this adapts whenever more content it shows scrollbar.
> 
> image

this is already there. i have set 100vh in body.modal-open to stop scrolling of background, when modal opens.

**Comment by denvamsi** [comment]
This is your Dep : https://covid19india-react-git-fork-binu42-modal.covid19india.now.sh/database

You can see on the model, Background scroll is stopped thats fine, But it looks very ugly now.

image


Here is my fix difference :

https://covid19india-react-git-fork-denvamsi-patch-1.covid19india.now.sh/database

image

**Comment by thahir007cp** [comment]
Could you please change that blue overlay to something like black or gray and changing a few text colors to black also appreciated. This look like a blue screen :)

**Comment by denvamsi** [comment]
Yes thats an wonderful one :)

**Comment by Binu42** [comment]
@denvamsi thanks. 

> Yes thats an wonderful one :)

thanks now it all working. i.e. stopped scrolling of page when modal is open and close the modal from anywhere outside modal on click.

**Comment by Binu42** [comment]
> Could you please change that blue overlay to something like black or gray and changing a few text colors to black also appreciated. This look like a blue screen :)

check it out here:- https://covid19india-react-fv78pcoo4.now.sh/database

**Comment by thahir007cp** [comment]
> > Could you please change that blue overlay to something like black or gray and changing a few text colors to black also appreciated. This look like a blue screen :)
> 
> check it out here:- https://covid19india-react-fv78pcoo4.now.sh/database

Much better. Thank you for taking care of that

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! As mentioned in the [contributing](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) guide, please have an issue filed first, have it accepted, then assigned to you before submitting a PR :)

This will help us discuss any changes/requirements before work is done on it!

**Pull request closed without merging**
