### PR TITLE
Re-designed home. Added cards. Please see attached screenshot

### PR DESCRIPTION
**Pull request by vivek-manjunath**
Redesigned home

### CODE REVIEW

**Comment by limshark** [comment]
UX wise , this is my suggestion 
1) First row title
2) Second row  Menu   ( left side key menu items ) Right side FAQ
3) Third row - Key Stats number as shown now
4) Fourth row - Key Graphs 
5) fifth row - left half table , right half India's map.

**Comment by denvamsi** [comment]
This looks very cool, But the header doesnt match. Can you try decreasing some font size and align menu items to center or float them left :)

**Comment by denvamsi** [comment]
And the main thing is in mobile it isnt very responsive :)

**Comment by denvamsi** [comment]
You can see below screenshot, The cards are going out of the box.

WhatsApp Image 2020-04-06 at 11 28 04 AM

**Comment by vivek-manjunath** [comment]
Improved responsiveness. Please take a look
COVID-19 Tracker  India

**Comment by denvamsi** [comment]
image
Is it looking good ? :)

**Comment by vivek-manjunath** [comment]
Please have a look now. 

image

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! Unfortunately, we'll not be moving forward with this redesign. However, thank you so much for your patience - feel free to open PRs against available issues :)

**Pull request closed without merging**
