### PR TITLE
Feat: Add containment zones to map

### LINKED ISSUE #1040: Add containment zones as they get declared
**Is your feature request related to a problem? Please describe.**
New containment clusters are being declared by the govt with different severity levels. It would be helpful to add them to this project

**Describe the solution you'd like**
A new page with the map color coded to match the govt's data.
eg:
Red- Total lockdown
Orange- Partial lockdown
Yellow - Community guidelines

**Additional context**
[Covid-19 containment zones in Delhi](https://economictimes.indiatimes.com/news/politics-and-nation/covid-19-containment-zones-in-delhi-rises-to-43/articleshow/75110988.cms)
Although this link doesn't describe the severity levels, I'm assuming that will come when more data for more districts becomes available.
This might be helpful to identify which zone can resume economic activity.

### PR DESCRIPTION
**Pull request by shuklaayush**
**Description of PR**
This PR adds containment zone visualization to the map. Also refactored map code and replaced India topojson with one containing district information.

**Relevant Issues**  
Fixes #1040

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
image

### CODE REVIEW

**Comment by ipimran** [comment]
Is it feasible to show state boundaries ?

**Comment by aswaathb** [comment]
@shuklaayush Do you think it'd be a good idea if you resized the zone colour bars at the bottom wrt the number of districts in each zone? like a stacked horizontal bar? Looks good through!

**Comment by TheDominus** [comment]
Just a suggestion.
1. We can have a toggle option for state or district 
2. Adding to 1, we can disable this option for zones for now. [We can able it later on once we know zones at the state level.]

**Comment by jeremyphilemon** [comment]
hi

**Pull request merged**
