### PR TITLE
Feature-  Automatically  update the page after specified Interval

### LINKED ISSUE #300: Update the data on page after every 15 / 20 mins
**Description**
If you kept the page open for a long time it doesn't update the page automatically.
For example Currently, when you load the page first time it fetches the latest updated data and shows last updated is 10 min ago Now when you keep the tab open for a long time or minimize the browser (In case of the mobile device) and back again after 2 hours it still shows Last updated 10 min ago and data is not updated and this creates confusion to the user. therefore the user needs to reload the page manually.

**Solution**
After reloading the page hit the API to fetch the data after every 15 to 20 mins (any suggestion on time intervals are welcome) and according to that update the page. So that it keeps the page updated, as well as the user need not reload the page manually.

### PR DESCRIPTION
**Pull request by chinmaydalvi**
**Description**
- This PR implements the feature to automatically updates the page after a specified interval. Currently, the interval is set to 15 minutes and it is configurable.
- Avoided the unwanted rendering for some components during automatic update of the page.
- Added Animated Loader just below the Last updated time of the page. Refer snapshot.

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #300 

**Checklist**

- [x] Compiles and passes ES Lint
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Screenshot 2020-04-06 at 3 47 48 AM

### CODE REVIEW

**Comment by chinmaydalvi** [comment]
Hi @jeremyphilemon 

I have raised the PR #711 for the automatic update feature. 
Please have a look.



Thanks and Regards
Chinmay Dalvi

**Review by faisal3389 — CHANGES_REQUESTED** [review]
Can you remove the .npmrc file as you have added it to the .gitignore

**Comment by chinmaydalvi** [comment]
> Can you remove the .npmrc file as you have added it to the .gitignore

@faisal3389  Deleted

**Comment by jeremyphilemon** [comment]
Hey @chinmaydalvi, thanks so much for taking the effort to submit this PR! Unfortunately I'm gonna have to close this because with our current gh-pages infrastructure, a manual refresh has been much more helpful in dealing with production updates being pushed and having the cache refreshed.

**Pull request closed without merging**
