### PR TITLE
adding totals row to the top, summary on top would be helpful for most cases

### PR DESCRIPTION
**Pull request by jayanthkaturi**
**Description of PR**

Summary row on the top would be helpful as user may be looking for one or two states and then country wide summary at any given point.

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Total on the top

### CODE REVIEW

**Comment by aseef17** [comment]
@jayanthkaturi 
Don’t really see a merit in this addition. But if you’re adding the total row to the top, might as well keep it fixed while scrolling

**Comment by jayanthkaturi** [comment]
@aseef17 Good idea, fixed total row on scroll.
image

**Comment by aseef17** [comment]
@jayanthkaturi 
Maybe you could fix the label and the count header without the space in between. Just a suggestion to make it easier on the eye

image

**Comment by jayanthkaturi** [comment]
Fixed it. Let me know if it doesn't work.

**Comment by aseef17** [comment]
@jayanthkaturi 
Doesn’t seem to work still
image

**Comment by jayanthkaturi** [comment]
Checked it on my mobile/chrome dev tool, could please tell me the resolution or phone model?

**Comment by aseef17** [comment]
> Checked it on my mobile/chrome dev tool, could please tell me the resolution or phone model?

Phone Model - iPhone XR
Resolution - 1792 x 828 px

**Comment by jayanthkaturi** [comment]
Unable to reproduce the issue, any chance it's a cached version?
image

**Comment by aseef17** [comment]
> Unable to reproduce the issue, any chance it's a cached version?
> 
> image
> 
> 
> 
> 

Seems like it was cached. Works fine now 👍🏽

**Comment by jayanthkaturi** [comment]
Thanks @aseef17

**Comment by shuklaayush** [comment]
Please read the [Contributing Guidelines](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) before creating a PR

**Pull request closed without merging**
