### PR TITLE
Fix: Debounce input events on search in home page

### LINKED ISSUE #1511: Search in home page freezes
**Describe the bug**
Search bar gets hang while finding something

**To Reproduce**

Go to 'Home Page'
Click on 'Search'
Start Typing
See error
Play around with the search, at some point it'll start to lag, and then hand completely.

**Expected behavior**
Search Bar should work properly without hanging.

### PR DESCRIPTION
**Pull request by chinmaydalvi**
**Description**

Fix the issue of Freezing of Search Bar while typing.
Used Debounce to fix the issue as well as to prevent unnecessary network calls & optimize the performance

**Relevant Issues**  
Fixes #1511 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

1. Typing Maharashtra
Typing Maharashtra (1)

2. Typing Madhya Pradesh
Typing Madhya Pradesh (1)

### CODE REVIEW

**Comment by chinmaydalvi** [comment]
@jeremyphilemon 
Please have a look as it can be High Priority.

**Comment by jeremyphilemon** [comment]
@chinmaydalvi hey thank you, this looks good! I see that you've used a debounce hook. We're currently using `react-use` and it has a `useDebounce` [hook](https://github.com/streamich/react-use/blob/master/docs/useDebounce.md) already defined, would it be possible if you could use that if they're both performing the same function? :)

**Comment by chinmaydalvi** [comment]
@jeremyphilemon Ok Let me try.

**Comment by chinmaydalvi** [comment]
@jeremyphilemon 

Used `useDebounce` Hook  from  `react-use` &  working fine.

**Comment by chinmaydalvi** [comment]
@ravindranrahul
For your issue #1486 solution might be the same which I have implemented.
Use the inbuilt  `useDebounce` hook which is already defined in `react-script`

**Comment by jeremyphilemon** [comment]
Awesome, thanks :D

**Pull request merged**
