### PR TITLE
Redirect to homepage on clicking the icon in NavBar

### PR DESCRIPTION
**Pull request by vairavlaksh**
On click of image will redirect
to home page

Signed-off-by: Vairav Lakshmanan <vairavan.lakshmanan@kaplan.com>

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
@JunaidBabu @sudevschiz thoughts on logo href-ing to GitHub org?

@vairavlaksh checked it out locally, doesn't seem to work as expected, can you check again?

**Comment by vairavlaksh** [comment]
> @JunaidBabu @sudevschiz thoughts on logo href-ing to GitHub org?
> 
> @vairavlaksh checked it out locally, doesn't seem to work as expected, can you check again?

@jeremyphilemon Irrespective of which page you are in, if you click on the logo it'll redirect to our home page ("/home"). It's working fine for me in the local. It'll not href-ing to Github org.

**Comment by iamsh4shank** [comment]
Are you working on this issue?

**Comment by vairavlaksh** [comment]
> Are you working on this issue?

Raised the PR. Now it'll link to home page

**Comment by iamsh4shank** [comment]
As the home page is present there it will be great if it will redirect to a different page.

**Comment by vairavlaksh** [comment]
But usually in any app, it'll redirect only to the homepage right. Wherever you are in, if you click on the image it'll redirect to the homepage only.

**Comment by vairavlaksh** [comment]
Closes #186

**Comment by iamsh4shank** [comment]
Ok I am closing that issue.

**Comment by iamsh4shank** [comment]
I think you can open a different link as two buttons for same thing will be not of any use.

**Comment by s-naveen** [comment]
IMO it's good to have logo redirect to homepage. It's a general thing followed on most websites.

**Comment by iamsh4shank** [comment]
Ok then

**Comment by jeremyphilemon** [comment]
We will not be hyperlinking the image since we already have a home button in the navbar right next to it, thanks!

**Pull request closed without merging**
