### PR TITLE
Fullscreen

### LINKED ISSUE #415: India Map and spread trends should swap their position when hovering on the below half of the state-table
when hovering on the down half part of the state wise information table it is impossible to see the India map. corresponding state Map and Spread Trends  should swap their position.

### PR DESCRIPTION
**Pull request by Binu42**
**Description of PR**
full screen opening of map and table in desktops for easy comparison.

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #415 #717 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
#### Demo view
demo

### CODE REVIEW

**Comment by denvamsi** [comment]
Wow, This is an fantastic feature and it is very useful. Previous i thought it is not more convenient to see the map along with bottom states, Now it looks super cool though needed some tweaks i think. I hope maintainers can encourage this feature :) @jeremyphilemon @sudevschiz

**Comment by Binu42** [comment]
> Wow, This is an fantastic feature and it is very useful. Previous i thought it is not more convenient to see the map along with bottom states, Now it looks super cool though needed some tweaks i think. I hope maintainers can encourage this feature :) @jeremyphilemon @sudevschiz

Thanks, man. i hope maintainers will think for it and give their suggestions. if you want to suggest/tweak something please tell me.

**Comment by denvamsi** [comment]
Its simply awesome ;) I think you can change scrollbar color to  #201aa2, So it matches with the primary theme :)
image

**Comment by Binu42** [comment]
> /rebase

@JunaidBabu done

**Review by jeremyphilemon — CHANGES_REQUESTED** [review]
@Binu42 Hey, we can move forward with this. Can you make the scrollbars hidden however and have it shown default like that, without the need to go fullscreen?

Also squashing and rebasing your commits will be nice :)

**Comment by Binu42** [comment]
> @Binu42 Hey, we can move forward with this. Can you make the scrollbars hidden however and have it shown default like that, without the need to go fullscreen?
> 
> Also squashing and rebasing your commits will be nice :)

@jeremyphilemon i tried the way you mentioned here (`i havn't pushed the recent code yet`), working fine but it will be not proper design for users particularly naive users they will miss the information for sure because scrollbar will be hidden, then issues related with it will start coming.

BTW i have resolved the conflicts have a **look at most recent deployment**, if you like it then we can adjust few things and give our users Full screen functionality.

**Comment by jeremyphilemon** [comment]
Hey thanks for getting back! 

So it looks like the fullscreen mode works only on chrome and not on safari? About the scroll bar, I agree with you. We can rather style the scrollbars to be thinner like

```
::-webkit-scrollbar{background-color: whitesmoke; width: 4px; height: 0;}
::-webkit-scrollbar-thumb{background-color: #bdbdbd;}
```

**Comment by Binu42** [comment]
> Hey thanks for getting back!
> 
> So it looks like the fullscreen mode works only on chrome and not on safari? About the scroll bar, I agree with you. We can rather style the scrollbars to be thinner like
> 
> ```
> ::-webkit-scrollbar{background-color: whitesmoke; width: 4px; height: 0;}
> ::-webkit-scrollbar-thumb{background-color: #bdbdbd;}
> ```

@jeremyphilemon agreed, i'll work on it.

**Comment by Binu42** [comment]
@jeremyphilemon done it, i have adjusted few things accordingly in desktop, have a look and let me know if, any suggestions. 

currently, homepage is not aligned properly.

**Before alignment**
Screenshot from 2020-04-20 05-00-55

**After alignment**
Screenshot from 2020-04-20 05-00-38

**Comment by jeremyphilemon** [comment]
Hey @Binu42, I'm really sorry but we had to use a different strategy to be able to pin both the maps/timeseries graphs. Sucks for me to close this PR but I'll keep an eye out on your future PRs, I've seen that you've put in a lot of work into them and your contributions have been very valuable :)

**Pull request closed without merging**
