### PR TITLE
Fix visualization problem

### PR DESCRIPTION
**Pull request by strikertanmay**
Fix regarding this Issue https://github.com/covid19india/covid19india-react/issues/403.
It happens for narrow screens, so I changed the SCSS for that particular media query.

### CODE REVIEW

**Comment by dpnkrpl** [comment]
Yeah, That worked ! 😊

**Comment by jeremyphilemon** [comment]
:/

Screen Shot 2020-04-03 at 9 35 17 PM

**Comment by strikertanmay** [comment]
> :/
> 
> Screen Shot 2020-04-03 at 9 35 17 PM

Please check once again. Let me know if problem still exists.

**Comment by jeremyphilemon** [comment]
Adding multiple media queries wouldn't be the desired strategy here. Let's have a discussion at #402 on the strategy :)

**Pull request closed without merging**
