### PR TITLE
PWA Feature Added

### LINKED ISSUE #78: PWA | Add to Home Screen Support
Can we include Add to Home Screen support for Chrome on Android?

Just went through the public folder on the source code and realized we need to a service worker script and include bigger icons in the manifest.

### PR DESCRIPTION
**Pull request by ssadev**
Hello, I have added the PWA(Progressive Web App) feature in this great project. First of all, I want to thanks to the creator of this project for making such a great thing to help people by giving them information with such a great UI experience. When I opened up the Issues section of this opensource project I saw that there are some feature requests for making an android app.  So I thought why I don't just help this project by making PWA that will fully perform like a native android application and help people to get information without opening a browser and then type the web address again and again. Because after clicking on 'add to home screen' in the browser it will show up like other native app in the app list  + home screen. Also when users click on that app icon it will open directly. No address bar, nothing will show or disturb from browser.

### CODE REVIEW

**Comment by aekanshd** [comment]
What's the status of this? Is it merged? @programworld999 We could also deploy a TWA if you have a quick android app ready.

**Comment by ssadev** [comment]
> What's the status of this? Is it merged? @programworld999 We could also deploy a TWA if you have a quick android app ready.

Sorry but I don't understand what do you mean by TWA? Do you mean PWA?
If you are asking about PWA then my answer is "yes".

**Comment by s-naveen** [comment]
@programworld999 can you share a running preview build?

**Comment by rajathsn** [comment]
GitHub link https://github.com/rajathsn/covid19 for the code and apk file of web view app of webpage "www.covid19india.com"

**Comment by dhruvdutt** [comment]
@programworld999 Can you trigger the Now deployment again manually? Want to check deployment preview.

**Comment by ssadev** [comment]
> @programworld999 can you share a running preview build?



> @programworld999 can you share a running preview build?

Okay, give some time, please. I'm sending the link in few hours

**Comment by ssadev** [comment]
> @programworld999 can you share a running preview build?

https://covid19india-react-programworld999.netlify.com/

**Comment by ssadev** [comment]
### Covid19india.org PWA Performance
Reason : 
* Showing "Add To Home Screen" vary quickly in mobile browser(chrome) : 

WhatsApp Image 2020-03-28 at 11 09 04 PM

* Fully behave like native app + getting full support from Android : 
(After Adding In home [Realme])
WhatsApp Image 2020-03-28 at 11 09 04 PM (1)

* It even works on desktop too : 

IMG_20200328_232620

After installing : 

Screenshot from 2020-03-28 22-44-08

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! We are currently not looking to support PWAs at the moment. With that said, feel free to have a look around issues and pick any accepted issues for a potential PR!

I went through the code, you really put a lot of effort into it, but thanks! Really appreciate it :)

**Comment by dhruvdutt** [comment]
@jeremyphilemon Any specific reason to not support PWAs at the moment?
IMHO it would be really useful. This is something which people would tend to open very frequently everyday. For mobile users, opening this inside a browser tab and refreshing it every time and finding it when there are multiple tabs is very bad experience.
PWAs for mobile would greatly improve retention.

**Comment by ssadev** [comment]
> Hey thanks for the PR! We are currently not looking to support PWAs at the moment. With that said, feel free to have a look around issues and pick any accepted issues for a potential PR!
> 
> I went through the code, you really put a lot of effort into it, but thanks! Really appreciate it :)

Thanks a lot for @jeremyphilemon  your appreciation. You appreciate my code this a lot for me. But if you need PWA for this any time I would like to request you to take my PR. Thank You.

And You know that my PWA is perfect: 
https://googlechrome.github.io/lighthouse/viewer/?psiurl=https%3A%2F%2Fcovid19india-react-programworld999.netlify.com%2F&strategy=mobile&category=performance&category=accessibility&category=best-practices&category=seo&category=pwa&utm_source=lh-chrome-ext#pwa

Screenshot from 2020-03-30 17-36-16

**Pull request closed without merging**
