### PR TITLE
changes for localization issue

### PR DESCRIPTION
**Pull request by kumargulshan91**
Fixes # for issue 1795 e.changeLanguage is not a function

### CODE REVIEW

**Comment by kumargulshan91** [comment]
#1795 fix for this issue

**Review by ab14bhardwaj — COMMENTED** [review]
@kumargulshan91 I really appreciate you for your contribution.
Just a suggestion, add package-lock.json to gitignore or else don't commit it.
Thanks

**Comment by bee-rickey** [comment]
Hi @kumargulshan91 did you have a read about the contributing guidelines: https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md ? Please do not fix an issue unless one of the mods has a look at the issue.

**Comment by jeremyphilemon** [comment]
Patched by #1862

**Pull request closed without merging**
