### PR TITLE
Change of table head to sticky table head

### PR DESCRIPTION
**Pull request by SanjeevYadavcr7**
I've changed normal table head to sticky table head. Hope this the change that you needed in the table.

### CODE REVIEW

**Comment by sudevschiz** [comment]
Could you share a screenshot of the change?

**Comment by SanjeevYadavcr7** [comment]
Here are the screenshots for the changes made in table head.

**Comment by SanjeevYadavcr7** [comment]
Corono1
Corona2

**Comment by sudevschiz** [comment]
Is this referencing any previous issue?
What is the design goal in doing this?

**Comment by SanjeevYadavcr7** [comment]
The issue is when you scroll down home page then table header gets hidden and user is not able to see the table header because of which it seems difficult to observe the data.

**Comment by sudevschiz** [comment]
Ah okay.

#179 . Our bad that multiple people worked on this. @JunaidBabu review?

**Comment by SanjeevYadavcr7** [comment]
Please make sure to close the issue once it is resolved.

**Comment by jeremyphilemon** [comment]
Thank you, we merged the PR that was submitted earlier!

**Pull request closed without merging**
