### PR TITLE
feature #136 : Log scale switch for cumulative charts

### LINKED ISSUE #136: Log graphs
Covid-19 is an exponential disease.

Looking at a simple graph really does not give true picture of cases.

Log graph will give correct picture on whether the disease is slowing down or further accelerating.

If possible, have log graph on a per state basis

### PR DESCRIPTION
**Pull request by imjaypatel12**
- Added Logarithmic switch on right pane. This is available only for Cumulative charts and not for daily charts.
- Added SI format for numbers on scale (Although I hope it never reaches there, numbers fall out beyond 9999 on Y-axis without this)
- Fixes #136

### CODE REVIEW

**Comment by shuklaayush** [comment]
@imjaypatel12 Looks great, but the UI breaks on phone. Maybe, shorten it to just Log.

image

PS: @jeremyphilemon I think we might have to remove the toggle and instead make the text clickable.

**Comment by imjaypatel12** [comment]
> @imjaypatel12 Looks great, but the UI breaks on phone. Maybe, shorten it to just Log.
> 
> image
> 
> PS: @jeremyphilemon I think we might have to remove the toggle and instead make the text clickable.

Thanks @shuklaayush for reporting it. It's fixed now.
image

**Comment by imjaypatel12** [comment]
This is weird now... im on it. I do not know whether I should create a new ticket for it or not. I am going to push this change in the same PR. Let me know if this doesn't align with your defined procedures.
image

Edit: Fixed now

**Comment by shuklaayush** [comment]
Hey @imjaypatel12, not sure why but the commit history and diff of this PR seems screwed up. Any way you can rebase --> force-push, or open a new PR based on the current master?

**Comment by imjaypatel12** [comment]
@shuklaayush I noticed that too, but I just don't seem to understand why is it showing all these intermediate commits as part of the PR. All I did was pull-rebase to resolve conflicts. Even the current diff of 2 branches from new PR page shows only 6 commits -- all of which are mine. 
https://github.com/covid19india/covid19india-react/compare/master...imjaypatel12:issues/136?expand=1
image

Anyway, I am going to rebase again to resolve conflicts and will see if that resolves this.

**Comment by shuklaayush** [comment]
@jeremyphilemon Any idea why this might be the case?

**Comment by imjaypatel12** [comment]
@shuklaayush alright, I did the `merge` instead of `rebase` and the issue is magically disappeared, shows only 3 files changed now :). But, the deployment failed :/ What the heck, i just accepted your changes in merge, and its working fine on local too. Also, I cant see the failure reason from the bot link, it gives 404.

**Comment by shuklaayush** [comment]
@imjaypatel12 That might be because of the compilation warning. Try fixing it, and push an update.

**Comment by shuklaayush** [comment]
@imjaypatel12 Found a bug. I think you forgot to accommodate for the lack of a log scale in the daily trend charts. You might need to add a check for the yScale based on the index as well.

Peek 2020-04-01 09-33

**Comment by imjaypatel12** [comment]
@shuklaayush oh no, that’s totally intentional (in fact, had to write some special cases to turn that damn switch off and not apply log scale logic for daily charts). I can't wrap my head around using log scale for daily counts, I think log scales are used only for exponential growth charts.

P.S. I should have thought about better word instead of `cumulative` in the PR title lol.

**Comment by shuklaayush** [comment]
@imjaypatel12 That's exactly what I'm saying. You've disabled the switch, but the daily trend graphs are still plotted on a log scale (which doesn't make sense).

**Comment by imjaypatel12** [comment]
Woah! Damn you’ve got some good eyes :D Let me fix that

**Pull request merged**
