### PR TITLE
Feature - Add count for total tests done uptil the latest data fetched.

### PR DESCRIPTION
**Pull request by huzefa-amura**
**Description of PR**

- We can now see the total number of tests done until the latest data fetched from covid19 API. It also shows the delta of tests.
- The total tests done count can be found besides the `Deceased` count. 

**Screenshot**
Screenshot from 2020-04-07 09-11-41

Relevant Issues:
https://github.com/covid19india/covid19india-react/issues/688

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

### CODE REVIEW

**Comment by denvamsi** [comment]
That's an useful feature. Btw there is some issue on mobile formatting, it doesn't have perfect alignment. Please check and resolve it :)

**Comment by huzefa-amura** [comment]
@denvamsi : Thanks !!! I hope this helps. 

I have fixed the alignment and have pushed the code for the same. Thanks!

**Comment by huzefa-amura** [comment]
@shuklaayush : After your force push, all tests have started failing. Can you please check ? 

It says `/nopt/package.json` not found.

**Comment by shuklaayush** [comment]
@huzefa-amura It's not related to the force push :sweat_smile:. Most commits are failing because of some changes to the CI. Don't worry about it.

**Comment by huzefa-amura** [comment]
@shuklaayush : Ok thanks !

Let me know once these CI errors are fixed then, I will re-deploy!

**Comment by jeremyphilemon** [comment]
Hey thanks for raising a PR! We've decided to have the testing stats place above the map instead. Thank you for taking the time to implement this, it'd also be better if you could work on issues that are labelled "available" and having them assigned to you before submitting your PR :)

**Pull request closed without merging**
