### PR TITLE
Add a toggle instead of a checkbox

### PR DESCRIPTION
**Pull request by sivasatvik**
A checkbox might be inconvenient for mobile users, hence adding a toggle instead.

Annotation 2020-03-26 133008

### CODE REVIEW

**Review by VigneshMurugan — APPROVED** [review]
Looks good.

**Comment by sivasatvik** [comment]
@jeremyphilemon , it seems other commits got added to this PR, should I open another PR with one commit?

**Comment by jeremyphilemon** [comment]
@sivasatvik hey im sooooo sorry haha! I think I messed up the git tree while helping you out with the rebase, could you open a new PR instead? Thank you so much!

**Comment by sivasatvik** [comment]
Alright, No problem. Here is the new PR: #311

**Pull request closed without merging**
