### PR TITLE
Added Rollup and configured it to minify maps file

### PR DESCRIPTION
**Pull request by tannakartikey**
**Description of PR**
The JSON files inside `public/maps` are not minified as they are easy to develop.
But we should serve minified files on the production. The PR uses the non-minified version on development and the minified maps on the production.

Added a task `compress_maps` which calls Rollup.
This task is added in `build` task so that the maps are compressed on each deploy.

The original size of the folder is 1.7M and the size of the compressed folder is 916K.

**Relevant Issues**  

**Checklist**

- [ ] Compiles and passes lint tests
- [ ] Properly formatted
- [ ] Tested on desktop
- [ ] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Comment by tannakartikey** [comment]
~~We need to modify the `build` command on ZEIT now when we merge this.~~

Fixed with: https://github.com/covid19india/covid19india-react/pull/1623/commits/ba34e3d628b340b0fefa04931f6c2b8bba3a6e03

**Comment by shuklaayush** [comment]
@tannakartikey Can't we just always keep the map files as minified JSONs, and exclude them from prettier formatting? Won't have to add dependencies then

**Comment by tannakartikey** [comment]
@shuklaayush actually it was minified first. Then we made it pretty.

It's hard to read the files and the properties when it is minified. Also, when the maps get updated, we can't tell what got updated.

Rollup is a dev dependency so it won't affect the performance of the app for the users.

**Comment by jeremyphilemon** [comment]
@tannakartikey This build seems to be working on zeit, will it work on gh-pages as well? 🤔

**Comment by tannakartikey** [comment]
@jeremyphilemon they both static servers so I don't think it will create trouble.

**Comment by tannakartikey** [comment]
How are we deploying to gh-pages? As long as we have `maps_data` folder which is generated as a result of `npm run build` we should be fine.

**Comment by jeremyphilemon** [comment]
@tannakartikey It still looks like the maps being downloaded on the production website aren't the minified versions? Am I seeing in the wrong place?

Screen Shot 2020-05-04 at 2 59 03 AM

**Comment by tannakartikey** [comment]
@jeremyphilemon I am not sure how you are viewing this inside Source tab. I couldn't find the file there.

Anyways, following are the response we are getting from the server:
From `master`:
image


From this PR:
image


Notice that the whitespace is gone.

You will see the same if you run the task on local and then check the files inside `mini_maps`

**Review by jeremyphilemon — APPROVED** [review]

**Pull request merged**
