### PR TITLE
Added setup commands for windows

### PR DESCRIPTION
**Pull request by Rajanpandey**
Done for issue: https://github.com/covid19india/covid19india-react/issues/171

### CODE REVIEW

**Review by manigandan-dorairaj — COMMENTED** [review]
Please hold on. While this method works on windows, it doesn't provide hot reload feature, which is very helpful to quickly see the changes getting reflected.

**Comment by Rajanpandey** [comment]
True.
Temporarily, what I do is:
Remove PORT=3000 from here "react-scripts start css-watch"
npm start
Restore PORT=3000 in "react-scripts start css-watch"

**Comment by Rajanpandey** [comment]
@manigandan-dorairaj Please check the new update.
@sudevschiz Inspired from your PR https://github.com/covid19india/covid19india-react/pull/197. This works.

**Comment by manigandan-dorairaj** [comment]
Yes, it works. Thanks!

**Comment by aar-1** [comment]
Hi Rajan - can you check PR 197 again ? It has updates for setting at specific port other than default one

**Comment by jeremyphilemon** [comment]
Closing since #197. Feel free to reopen an issue if you're still having trouble with installing and starting the application :)

**Pull request merged**
