### PR TITLE
Highlight state boundaries on map when hovering

### LINKED ISSUE #119: State selected in table should be highlighted in map and subsequent details should be shown.
when we select or hover on a state in table , automatically that respective state will get highlighted in map and subsequent detail should be shown , and it should also happen vice versa !

Screenshot from 2020-03-25 22-58-32

### PR DESCRIPTION
**Pull request by shuklaayush**
Complementary to #137. Fixes #119. 

Peek 2020-03-27 16-00

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Good stuff! I think there's a small bug, when the mouse leaves the table, the state in the map remains, and when hovering over the map the state's stroke still remains!

**Comment by shuklaayush** [comment]
~~Hey @jeremyphilemon! Can't reproduce what you're saying. Can you attach a gif?~~
@jeremyphilemon Nevermind, fixed it. 
https://covid19india-react-git-fix-map-hover.shuklaayush.now.sh

**Comment by radhasatam** [comment]
Looks good.

**Comment by jeremyphilemon** [comment]
@radhasatam @shuklaayush Heads up, district maps are up! ;)

Click on state to navigate.

**Pull request merged**
