### PR TITLE
Feature: Localization support (#357, #432)

### PR DESCRIPTION
**Pull request by harshzalavadiya**
**Description of PR**
@jeremyphilemon, In response of https://github.com/covid19india/covid19india-react/pull/432#issuecomment-607540009
- Due to no cases in that area this was causing crash because of no `undefined` check
- All given languages are already added as of now I have arranged in that order
- all locale templates are available in `public/locales` directory and order for dropdown can be set from `src/i18n/locales.json`

**Type of PR**

- [x] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
localization

Let me know if I have missed anything

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Can you do an interactive rebase and drop the commits before your three commits and force push?

Or check the "allow maintainers to commit" and I'll fix it for you :)

**Comment by harshzalavadiya** [comment]
@jeremyphilemon

I tried rebasing since option wasn't available but failed so I have reverted rebase 😝

Turns out you can't have allow edit from maintainers from and org so I have transferred it to my profile and option came suddenly 😂

If you are able to do rebase and if you don't mind can you please share commit hash on which it was rebased edit file diff or better screen recoard? I might be able to learn from that and avoid similar situation in future

**Comment by jeremyphilemon** [comment]
Haha no problem! Rebasing can be tricky, but it's your swiss army knife when used properly. 

How I rebased: 
https://storage.googleapis.com/jrmyphlmn/images/github/first.gif

And after the merge conflicts were taken care of, I made a commit called "Rebased." and:
https://storage.googleapis.com/jrmyphlmn/images/github/second.gif

**Comment by harshzalavadiya** [comment]
@jeremyphilemon thank you for gifs really helpful, 

I tried doing it with previous checkout locally and turns out I was just freaked out by looking at merge conflicts and didn't realize that there's something called `git rebase --continue` and thought that git will automagically merge everything 😂

**Comment by jeremyphilemon** [comment]
@harshzalavadiya Haha! I hope from next time onwards you don't freak out :P

Also, can you explain what the workflow would look like to add a new translation? I've installed i18n-ally on vscode, what would be the next steps? 

I'll also link the folks here if they're looking to add more languages.

**Comment by harshzalavadiya** [comment]
@jeremyphilemon 
to add more languages you just have to create one new file and one new entry I have described it [here](https://github.com/covid19india/covid19india-react/blob/feature/localization/CONTRIBUTING.md#adding-new-language)

language codes are taken from google translate codes so `i18n-ally` can automatically recognize language

If you want to bulk translate JSON you may try https://marketplace.visualstudio.com/items?itemName=leizl.translate (usable with temp json that will take en and translate to selected language) this might be fastest way instead of using google sheets to translate which I did initially flattening key translate and then unflatten

adding new key is easy if you have `i18n-ally` installed on vscode.

Adding new key

---
Edit for reference: Add this configuration in your `.vscode/settings.json` if you install the plugins for vscode.
```
"i18n-ally.localesPaths": ["public/locales", "src/i18n"],
"i18n-ally.keystyle": "nested",
"i18n-ally.sourceLanguage": "en"
```

**Comment by jeremyphilemon** [comment]
That's awesome! I just made a translation for Malayalam, still requires a lot of effort! You must taken so much time to get this done! Thank you so much :D

Also I'm not sure if folks would open PRs on localization and translations, but I'm sure there will be issues. I'll tag them as localization, so if you're good feel free to open PRs for them. I'll definitely keep an eye out for them!

**Pull request merged**
