### PR TITLE
Updated the FAQ & Link Page styles

### PR DESCRIPTION
**Pull request by thahir007cp**
I have tweaked color and font style of FAQ to match it with rest of pages

**Description of PR**

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

**Now**
Screenshot 2020-04-04 at 10 25 43 PM

**Then**
Screenshot 2020-04-04 at 10 25 33 PM

### CODE REVIEW

**Comment by meghna-saxena** [comment]
@thahir007cp maybe you can apply the same styles on `/links` page as well, it will be a consistent style throughout then.

**Review by meghna-saxena — APPROVED** [review]

**Comment by thahir007cp** [comment]
Sure I will do that

**Comment by thahir007cp** [comment]
> @thahir007cp maybe you can apply the same styles on `/links` page as well, it will be a consistent style throughout then.

Please check now https://covid19india-react-git-fork-thahir007cp-master.covid19india.now.sh/links

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! As mentioned in the [contributing](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) guide, please have an issue filed first, have it accepted, then assigned to you before submitting a PR :)

**Pull request closed without merging**
