### PR TITLE
Search bar essentials

### PR DESCRIPTION
**Pull request by g-bhagwanani**
**Description of PR**
Added columns in the scope of search bar
Searched keyword marked in yellow in searches
Added proper padding for the search bar

**Type of PR**

- [x] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

*Mobile:*
mobile view

*Desktop:*
desktop view

### CODE REVIEW

**Review by tannakartikey — CHANGES_REQUESTED** [review]
Let's remove all the `console.log` and comments from the code.

**Review by tannakartikey — CHANGES_REQUESTED** [review]
Can remove the blank file `src/components/Essentials/essentialstabledesktop.js`

**Comment by g-bhagwanani** [comment]
@tannakartikey I've deleted the empty file. There was just one console log on the essentials page, I've removed that.

**Comment by tannakartikey** [comment]
@g-bhagwanani actually, that error going to console.log was okay. But there are many other comments in the code. Can you please remove those too?
For example https://github.com/covid19india/covid19india-react/blob/a533686e1dcb66315b7273f55d7935a3fd54f573/src/components/Essentials/essentialsutls.js#L5

**Review by tannakartikey — APPROVED** [review]
LGTM

**Comment by g-bhagwanani** [comment]
@tannakartikey can you check now

**Pull request merged**
