### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by anukaal**
**Description of PR**

Changes the font weight

**Relevant Issues**  
Fixes #...

Changed The font-weight

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

### CODE REVIEW

**Comment by bee-rickey** [comment]
Why was the font weight changed?

**Comment by anukaal** [comment]
It will look good to increase the font weight

**Comment by bee-rickey** [comment]
> It will look good to increase the font weight

Have you read the guidelines for contributing?

**Comment by anukaal** [comment]
YES , I have read the guidelines for contributions.
You can verified whether it will look good by changing the font weight

**Comment by shuklaayush** [comment]
Do you mind adding a few before-after screenshots? And maybe update the PR title/descriptions so that people can get a summary of the changes

**Comment by bee-rickey** [comment]
> YES , I have read the guidelines for contributions.
> You can verified whether it will look good by changing the font weight

Usually I do not engage in these talks, but by looking at the PRs you've raised, looks like you did not read any guideline. There's no description of the changes, there's no screenshots, there's no bug associated with the PR.

**Review by sparsh-99 — CHANGES_REQUESTED** [review]
I suggest that we should go for the original font-weights. No need to update the file in my opinion. Thank You

**Pull request closed without merging**
