### PR TITLE
Changes for using start script in windows

### PR DESCRIPTION
**Pull request by aar-1**

### CODE REVIEW

**Comment by sudevschiz** [comment]
Can somebody on a windows system review this once?

**Comment by sudevschiz** [comment]
#177

**Comment by Rajanpandey** [comment]
@sudevschiz I am getting this. For some reason, it is not working.

Screenshot (43)

**Comment by s-naveen** [comment]
We can use [cross-env ](https://www.npmjs.com/package/cross-env)as dev dependency and use it to set port so we won't have any cross platform issues.

**Comment by aar-1** [comment]
Added changes to the command post which react-scripts start command is working as expected.

s-naveen or @Rajanpandey- can you check again ?
Refer:
image

Although - cross-env command can work - just wanted to use the native command - so that could avoid using additional dependency

**Comment by aar-1** [comment]
Closing as 177 got merged in master

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR and giving a temporary workaround for windows users! I'll be removing the PORT variable on the start script since it serves no purpose. Thank you, however :)

**Pull request closed without merging**
