### PR TITLE
feature: Darkmode

### PR DESCRIPTION
**Pull request by abhishekkhandait**
Added darkmode for visual ergonomics. 

Support for themes(light and dark) is also added. The current color scheme is used as 'light' theme and a new color scheme for dark mode is added.

### CODE REVIEW

**Comment by shuklaayush** [comment]
Is it possible to invert the map as well? Maybe something like this (Chrome with DarkReader):

Screenshot from 2020-03-25 22-37-45

**Comment by abhishekkhandait** [comment]
Dark reader applies some combinations of css filters. By simply applying invert(100%) filter over map svg it renders something like this
Screenshot 2020-03-25 at 10 56 05 PM

I am no expert in filters so need to check what combination gives the desired result.

**Comment by shuklaayush** [comment]
Okay. In my opinion, if the red text inverts as red in dark mode, then the red map should as well.

**Comment by shuklaayush** [comment]
@abhishekkhandait Hey! Adding a hue-rotate(180deg) filter after invert(100%) looks good enough. Can you add it and update the PR?

**Comment by abhishekkhandait** [comment]
@shuklaayush Done.

Screenshot 2020-03-26 at 6 22 32 PM

**Comment by s-naveen** [comment]
I did a similar thing didn't know it was already being done. IMO pure black is not good for reading texts it puts too much strain on eyes. We can go for dark gray. 

https://covid19-india-react-git-dark-mode.s-naveen.now.sh/

**Comment by shuklaayush** [comment]
I prefer pure black. It looks great on OLED screens.

**Comment by s-naveen** [comment]
No its not. As I said too much strain on eyes that defeats the whole purpose of dark mode. Most of the apps like Gmail, GitHub, youtube, whatsapp use some form of dark gray for dark theme.

If we really want to support black then we can give users option to choose between light/dark/amoled black.

**Comment by jeremyphilemon** [comment]
Hey, thanks for the PR! I feel it'd be best to have a discussion about the color palettes before moving on to the PR phase! 

Feel free to open an issue so that we can have a discussion and you can take this up!

**Comment by nikhilm19** [comment]
I have worked on something similar. Check it out
Screenshot 2020-04-11 at 9 18 22 PM

**Pull request closed without merging**
