### PR TITLE
Style: Dark mode palette for select dropdown 

### LINKED ISSUE #1421: Inconsistent select state and gender drop down in dark mode UI
Description:
The select state and gender drop down are not properly recognized as drop down buttons because of their color. 

1. Go to 'Menu'
2. Click on 'Demographics'
3. See error

Expected Behavior:
Select state and gender should have white tab to properly recognize them as drop down menu. 
Just like in light theme UI. 

Screenshot_2020-04-23-01-44-40-816_com android chrome

Screenshots:
Screenshot_2020-04-23-01-28-32-399_com android chrome

### PR DESCRIPTION
**Pull request by Achal1607**
**Description of PR**

This PR changes background color of select state,select district,select city and genders drop down so that it can be properly visible.

**Relevant Issues**  
Fixes #1421 

**Checklist**
 
- [x]  Compiles and passes lint tests
- [x]  Properly formatted
- [x]  Tested on desktop
- [ ]  Tested on phone
 

**Screenshots**
**Before:**
before
**After:**
after

### CODE REVIEW

**Review by jeremyphilemon — CHANGES_REQUESTED** [review]
@Anchal1607 Hey this looks good! However I completely read over the fact that you were gonna turn them light in the issue description. I think it would be better to have a lighter tone but dark for them as well. 

Could you try that please?

**Comment by Achal1607** [comment]
Okay I will try to do it..

**Comment by Achal1607** [comment]
is the new pull request meets all the requirements of yours..

**Comment by jeremyphilemon** [comment]
Hey @Achal1607, I went through your changes but unfortunately the palette used was inconsistent with the rest of the website. #1549 used an appropriate palette to fix the issue so I'm closing this in favor of that – it sucks for me to close this when the issue was assigned to you, but I hope you understand.

Feel free to open a new PR on available issues, I'll keep an eye out! :)

**Comment by Achal1607** [comment]
Hey **@jeremyphilemon** , No problem...I would keep contributing to your website...

**Comment by Achal1607** [comment]
But still the colour of calender is not according to the dark theme.

**Comment by shuklaayush** [comment]
Seems obsolete now since Demographics has been deprecated

**Pull request closed without merging**
