### PR TITLE
Fix: Matched style of select in demographics to that of homepage

### LINKED ISSUE #747: Why not style dropdowns on the Demographics and Fix the Description :)
**Is your feature request related to a problem? Please describe.**
No it is not, But a sweet styling :)

**Describe the solution you'd like**
The website has a whole new level of UI, But on the select dropdown styling is not good and didn't matched at all:)

**Describe alternatives you've considered**
I have written some CSS code, I know you can write more better :)

image

My CSS Code :
`select {
    background-color: #babbbc;
    cursor: pointer;
    min-height: 1em;
    outline: 0;
    border: none;
    vertical-align: baseline;
    background: #e0e1e2 none;
    color: rgba(0,0,0,.6);
    font-family: Lato,"Helvetica Neue",Arial,Helvetica,sans-serif;
    padding: 0.8em 1em;
    font-weight: 700;
    line-height: 1em;
    font-style: normal;
    text-align: center;
    text-decoration: none;
    border-radius: 0.3rem;
    user-select: none;
    transition: opacity .1s ease,background-color .1s ease,color .1s ease,box-shadow .1s ease,background .1s ease;
    -webkit-tap-highlight-color: transparent;
}
select {
    width: 10rem;
    margin-right: 0.25rem;
}`

**Fix for Description**
image

Can you please try making like this, so it looks good on visit instead of scrolling and we can understand more better :)

Thanks & Regards,
Vamsi

### LINKED ISSUE #852: Drop down menus don't follow ( on mobile devices) the website theme
Drop down menus do not maintain the entire website theme.

### PR DESCRIPTION
**Pull request by Binu42**
**Description of PR**
* styled dropdown menu across website.
*  prevented entry of invalid page number in input on essential page.

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #852, Fixes #747

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Screenshot from 2020-04-11 09-31-07

Screenshot from 2020-04-10 05-20-25

### CODE REVIEW

**Comment by mohitm15** [comment]
@Binu42 does not include my issue here.. do not mention the PR. I am already working on it

**Comment by denvamsi** [comment]
Hey there

**Comment by denvamsi** [comment]
https://imgur.com/a/qVlPg8O

Can you please check this issue when I select dropdown they go floating on left and right and the native full screen dropdown mobile is not much good :) it's my sweet issue.

**Comment by Binu42** [comment]
> https://imgur.com/a/qVlPg8O
> 
> Can you please check this issue when I select dropdown they go floating on left and right and the native full screen dropdown mobile is not much good :) it's my sweet issue.

@denvamsi i checked it out in my phone and one other also, it's just working fine, can you show some images or something.

**Review by jeremyphilemon — CHANGES_REQUESTED** [review]
Hey @Binu42, thanks for this PR! Could you use the styling of the dropdown used in the timeseries graph on the homepage? That would make the other selects more consistent with the design system implemented. 

Also would also like if you keep the fix for essentials in a separate PR as well. Thanks :)

**Comment by Binu42** [comment]
> Hey @Binu42, thanks for this PR! Could you use the styling of the dropdown used in the timeseries graph on the homepage? That would make the other selects more consistent with the design system implemented.
> 
> Also would also like if you keep the fix for essentials in a separate PR as well. Thanks :)

@jeremyphilemon done.

**Comment by denvamsi** [comment]
The new design looks very cool, But there are some issues as well.

1. Can you able to make the floating menu to be fixed instead of changing width on hover.
image

2. On the deep div page, Give equal padding to both sides left and right.
image

3. Give Some Padding to this box.
image

4. The cluster Hover tooltip going out of the box.
image

Thanks & Regards,
Vamsi

**Review by jeremyphilemon — APPROVED** [review]

**Comment by strikertanmay** [comment]
@jeremyphilemon Sorry to say but there are some bugs with UI in this PR.
rsz_screenshot_from_2020-04-17_22-18-08
 
rsz_1screenshot_from_2020-04-17_22-17-58 (1)

Just preview my changes and decide which one is good !!( https://covid19india-r-git-fork-strikertanmay-strikertanmay-fx-d-f63272.covid19india.now.sh)

**Pull request merged**
