### PR TITLE
Worked on descending order sorting of confirmed cases for districts

### PR DESCRIPTION
**Pull request by Shashwat-Goyal**

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Hey this looks good, could you please rebase?

**Comment by Shashwat-Goyal** [comment]
@jeremyphilemon I have rebased the changes from master. Please have a look.

Also, I really want to collaborate to the project so can you share some issues that I can help with because most of the others are already taken. 

Thanks!

**Comment by shuklaayush** [comment]
Nice work @Shashwat-Goyal! 
@jeremyphilemon I was wondering, should we treat the Unknown districts separately?

**Comment by Shashwat-Goyal** [comment]
Thanks! @shuklaayush For the unknown districts, earlier they were being treated separately but then for the sorting I thought we should merge them both. Let me know your thoughts and if any change is required so I will update the PR.

**Comment by jeremyphilemon** [comment]
Hey, this was patched by an earlier PR #181 ! Feel free to open future PRs on available issues :)

**Pull request closed without merging**
