### PR TITLE
Improv: Add service workers to PWA

### PR DESCRIPTION
**Pull request by anilgupta1591**
**Description of PR**
Added feature of Progeressive web app which will add functionality in app
1. Offline page will display when network is offline (If any checnges required let us know)
2. App will able to install in devices

**Relevant Issues**  
Fixes #...
1. Some changes in manifest.json
2.Added service-worker.json
3. Added offline.html page
4. registered service worker directly in index.html removed from index.js
**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Comment by anilgupta1591** [comment]
Some screenshot of implementation

Screenshot from 2020-04-26 17-22-33
Screenshot from 2020-04-26 17-23-12

**Comment by jeremyphilemon** [comment]
@anilgupta1591 hey thanks for the PR!

I have a few questions regarding this, when would the PWA app download an updated version of the site? We had enabled PWA temporarily yesterday, however, updates to the website were not getting reflected (I believe it was still showing the cached versions) one people's phones. 
I read up online that in order to do that, we'll have to follow a `network-first` strategy. 

I'd appreciate it if you could help me understand this problem and how we could potentially fix it :)

**Comment by anilgupta1591** [comment]
@jeremyphilemon  Hey Thanks to look into my PR.

I have tested my code over device and update the code and It was working.
Means it always take from network , we are not caching all site so no need to delete cache.

Updates of  website will be reflect as normal website, It will change only look and feel of user.
If network will offline then cached offline page will show/

I hope answered your question what you want to know.

**Comment by anilgupta1591** [comment]
I will be happy to contribute more, just let me know react or backend thing.
My contacts:
9300358503/anilgupta1591@gmail.com

**Comment by shuklaayush** [comment]
Added via #1829. Thanks for the PR though! :)

**Pull request closed without merging**
