### PR TITLE
District hover in the table changes the map and map stats 

### PR DESCRIPTION
**Pull request by yogigachinmath**
Integrated the district and state view with map, 
On Hover of State/UT, the state/UT on map get highlighted with the stats are been updated for both State/UT 
and for district view as well.

### CODE REVIEW

**Comment by shuklaayush** [comment]
@yogigachinmath Thanks for this! UX is awesome, though there seems to be a synchronization issue somewhere. It might be unrelated to your code.

Peek 2020-03-29 00-01

**Comment by yogigachinmath** [comment]
> @yogigachinmath Thanks for this! UX is awesome, though there seems to be a synchronization issue somewhere. It might be unrelated to your code.
> 
> Peek 2020-03-29 00-01

**Comment by yogigachinmath** [comment]
I will look at it

**Comment by yogigachinmath** [comment]
Hi, I have fixed the bug please check it out. There is one more bug, Initial hover is not working

**Comment by jeremyphilemon** [comment]
Just checked it out locally, looks good! Could you squash your commits and rebase over master?

**Comment by yogigachinmath** [comment]
> Just checked it out locally, looks good! Could you squash your commits and rebase over master?

Hi, I have already merged it, sorry i did not squash them.

**Comment by jeremyphilemon** [comment]
There seems to be some merge conflicts, take your time to get them resolved and push them :)

This looks good so looking forward to it!

**Comment by shuklaayush** [comment]
@yogigachinmath Thanks! It's coming together nicely. I found another small bug. If you stop hovering on a district in the table, it's still highlighted on the map. Then, if you go hover over the map, multiple districts are highlighted.

image

Also, some small merge artifacts need to be cleaned up.

**Pull request merged**
