### PR TITLE
[Feat]: Add Social Sharing Links

### LINKED ISSUE #2403: Implement a share feature
We can implement one share feature for a share a link of specific state data or region
- we can put the share button in /state/ route
- with the help of that user can share a whole state covid data[ LINK ] on other social media or [copy the link]
- furthermore, we can actually drill it down more like share a particular field like active cases, vaccinated, daily cases, etc.

### PR DESCRIPTION
**Pull request by Saptarshee94**
**Description of PR**

Social sharing links added on Maps for Facebook, Email, Whatsapp, Twitter. 
**Relevant Issues**  
Fixes #2403

### CODE REVIEW

**Comment by Code-Concorde** [comment]
Recommit

**Comment by Saptarshee94** [comment]
I nave recommitted code with some tweaks. CI Console is showing some permission errors.

**Comment by ravi-maithrey** [comment]
On line 347 of src/components/MapExplorer.js there is "CampersTribe - World is yours to explore" why was this added?

**Comment by Saptarshee94** [comment]
> On line 347 of src/components/MapExplorer.js there is "CampersTribe - World is yours to explore" why was this added?

PR updated with fix.

**Comment by shuklaayush** [comment]
Doesn't go with the design of the rest of the website and looks out of place

image

**Pull request closed without merging**
