### PR TITLE
Link shifted

### PR DESCRIPTION
**Pull request by sanair96**

### CODE REVIEW

**Comment by sanair96** [comment]
Moves the telegram join link and the crowdsouce database to the bottom. Prioritising information about COVID-19.
Screen-Recording-2020-03-24-at-3

**Comment by jeremyphilemon** [comment]
Looks good! Can you fix the merge conflicts?

**Comment by sanair96** [comment]
@jeremyphilemon  conflicts have been resolved

**Comment by sanair96** [comment]
#25 Solved here

**Pull request merged**
