### PR TITLE
Population :: Add a new column against each state mentioning the popu…

### LINKED ISSUE #209: Population :: Add a new column against each state mentioning the population or Cases/1M population
Population :: Add a new column against each state mentioning the population or Cases/1M population.

This will help understand how severe hit a state is.

### PR DESCRIPTION
**Pull request by iam-hitesh**
Fixes #209 

Added population.json file for getting population of different states and union territories, census data is taken from 
https://data.gov.in/resources/stateut-wise-overall-population-st-population-percentage-sts-indiastate-total-population

### CODE REVIEW

**Comment by iam-hitesh** [comment]
Added new column to table ie. cases/1M.
Please review and merge. And let me know if there any changes.

**Comment by abhinav098** [comment]
UI breaks on my mac 13" screen. 

Try making some change to the CSS.
.Home {
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    flex-wrap: wrap;
    margin-left: 5rem; # earlier it was 10rem
    margin-right: 5rem; # earlier it was 10rem
}

refer screenshot for the issue => 

Screenshot 2020-03-27 at 23 16 03

**Comment by shuklaayush** [comment]
Hi @iam-hitesh, see #221. I don't think we have enough space on the table to show this as well. The UI breaks on smartphones. It is an interesting metric, though. Maybe we can add it in a deep dive section (#141, #190). Closing.

**Comment by JunaidBabu** [comment]
We can add this later in our deep dive tab (in-progress)

**Pull request closed without merging**
