### PR TITLE
Feat: Add maps based on active, recovered, and deceased counts

### LINKED ISSUE #1388: Map showing percentage for active and deceased as well like confirmed
**Is your feature request related to a problem? Please describe.**
right now on the map when we hover we are seeing percentage of each state confirmed case
IMG_20200422_083546
so we are not able to see current active and deceased percentage as the overall percentage info is very helpful.
**Describe the solution you'd like**
so i would like to have a drop down at the top the map saying confirmed, active and deceased so if user selects he wants to see active percentage the map would change to show current active for all the state and also the color would chnage to green and similarly we would have a color range for green as well. so in that case states like goa we can easily know it has fully recovered by seeing the state in green color.

**Describe alternatives you've considered**
this is in ref to the discussion what i did in issue #1345

**Additional context**

### PR DESCRIPTION
**Pull request by shuklaayush**
**Description of PR**
Refactored code to plot maps based on active, recovered and deceased counts. Map types are switched by clicking on the respective panels above the map. The colours represent absolute values and are not normalized in any way (population, total cases etc.).

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #1388
Addresses #675

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Peek 2020-04-23 17-25

### CODE REVIEW

**Comment by keshank** [comment]
@shuklaayush Two suggestions.
1. If you can change the colour of borders for states when changing the map.
2. If you can add Tested to map as well

**Comment by shuklaayush** [comment]
@keshank Thanks for the suggestions. This is WIP. Don't worry about 1 and other styling issues. As for 2, it'll probably be added later if/when the data is available at district level

**Comment by gyanendrapatro** [comment]
I have changes which says about districtwise also

**Comment by gyanendrapatro** [comment]
And also the color on map should be like current active 0 means the state is green that gives moreninfo to the users like its a green state

**Comment by gyanendrapatro** [comment]
I have the changes if you want i can give a pr

**Pull request merged**
