### PR TITLE
Feature: Use Indian number system for yAxis all Graphs

### LINKED ISSUE #1787: Value in graph uses Indian numbering system, while axis uses international number system
**Describe the bug**
For example, in the "Tested" graph, the current value is shown as `11,07,233` while the Y-axis of the graph shows the numbers in millions like `1M`.

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Scroll down to "Tested" graph on the bottom right.
3. Select "All States" to show data for all states. (Bug is there even without this but based on current numbers it shows only when "All States" is selected.

**Expected behavior**
Numbering system used in graph should be consistent with numbering system used in the axis.

**Screenshots**
Screenshot 2020-05-05 at 6 55 12 PM

**Desktop (please complete the following information):**

- OS: OSX 10.15.4
- Browser: Chrome
- Version: 81.0.4044.129

**Additional context**
None

### PR DESCRIPTION
**Pull request by ayushya**
**Description of PR**

Data in the Graph uses Indian Numbering already, yAxis is using SI Numbering System, ie. 10Lakhs is represented as 1Million.

This PR Standardises the yAxis to use the Indian Numbering System.

**Relevant Issues**  
Fixes #1787 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Add relevant screenshots here
**Before**
Issue

**After**
After

### CODE REVIEW

**Comment by ayushya** [comment]
@shuklaayush 
Could you have a look at this PR, whenever you have some bandwidth?

**Comment by shuklaayush** [comment]
Hi @ayushya, it might be better to keep the decimal digits as long as they're not trailing zeros. Otherwise, the y axis could have redundant entries. 

image

**Comment by sudevschiz** [comment]
I think the SI system is the standard. It will help us in packaging the solution later and also in comparing the numbers with other countries. 

Since Indian school system teaches Lakhs and Millions equally, it's okay to retain this as is.

**Comment by bee-rickey** [comment]
The standard used for graphs is the SI system. After an internal discussion, it feels like all the mods agree on this. Closing this for now.

**Pull request closed without merging**
