### PR TITLE
Show active cases timeline - PR against issue #899

### LINKED ISSUE #899: Show graph for the number of current active cases (total cases - recorvered cases) by day for the entire country as well for each state

### PR DESCRIPTION
**Pull request by iDhruv22**
**Description of PR**
Show active cases timeline for total as well as daily bases
**Type of PR**

- [ ] Bugfix
- [✅] New feature

**Relevant Issues**  
Fixes #899 #825 

**Checklist**

- [✅] Compiles and passes lint tests
- [✅] Properly formatted
- [✅] Tested on desktop
- [✅] Tested on phone

**Screenshots**
image

### CODE REVIEW

**Comment by TheDominus** [comment]
@iDhruv22, For daily cases graph, some days has -ve active daily cases, i.e. the total number of new cases is less than recovered + deceased. But, in the graph  (16th Feb). It is showing 0. 
Do you think, there should be a negative scale too?

**Comment by trilloc** [comment]
Hi..

It may be sufficient to show total active cases. IMHO Daily recovered cases will be a good enough substitute for daily active cases.

Thanks
Rajesh

**Comment by iDhruv22** [comment]
> @iDhruv22, For daily cases graph, some days has -ve active daily cases, i.e. the total number of new cases is less than recovered + deceased. But, in the graph (16th Feb). It is showing 0.
> Do you think, there should be a negative scale too?

Yes understood your point. I think Zero is good enough in that case.

**Comment by iDhruv22** [comment]
// This logic will work now @TheDominus @trilloc 
```js
  totalactive: (() => {
    // Total Active = Confimed - Recovered - Deceased
    let _totalactive = +stat.totalconfirmed - +stat.totalrecovered - +stat.totaldeceased;
    // If it is negative then there are no active cases
    if (_totalactive < 0) return 0;
    return _totalactive;
  })(),
  dailyactive: (() => {
    // Daily Total = Daily Confimed - Daily Recovered - Daily Deceased
    let _dailyactive = +stat.dailyconfirmed - +stat.dailyrecovered - +stat.dailydeceased;
    // If it is negative then there are no active cases
    if (_dailyactive < 0) return 0;
    return _dailyactive;
  })(),

**Comment by shuklaayush** [comment]
Thanks for your help guys! I've fixed some stuff and raised another PR at #1250. Closing this

**Pull request closed without merging**
