### PR TITLE
Update missingLocaleServer.js

### PR DESCRIPTION
**Pull request by anukaal**
**Description of PR**

A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange feedback, and merge!

**Relevant Issues**  
Fixes #...
changes done in the localhost
**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Comment by bee-rickey** [comment]
Is there a problem with using 127.0.0.1? Why change it to localhost? Can you provide a proper description on the PRs you raise? Thank you.

**Comment by anukaal** [comment]
The hostname localhost is used to access the network services running on a host through the loopback network interface.Ordinarily only the address 127.0.0.1 is used for loopack. But you can change the loopback IP address to some other IP address by modifying the network configuration of the loopback network adapter and then pointing the localhost to the new IP address in the hosts file.
so it will more rellevent to use localhost

**Comment by bee-rickey** [comment]
> The hostname localhost is used to access the network services running on a host through the loopback network interface.Ordinarily only the address 127.0.0.1 is used for loopack. But you can change the loopback IP address to some other IP address by modifying the network configuration of the loopback network adapter and then pointing the localhost to the new IP address in the hosts file.
> so it will more rellevent to use localhost

Don't see how any of this adds value to the site. Please go through the guidelines for contributing. I'm keeping this open and allowing other mods to have a look.

**Comment by anukaal** [comment]
Yes , I have read the guidelines for contributions

**Pull request closed without merging**
