### PR TITLE
Added sitemap xml for better SEO and crawling

### LINKED ISSUE #1110: No sitemap available (SEO)
**Describe the bug**
Sitemap XML will help increase the reach and improve crawling and overall SEO.

### PR DESCRIPTION
**Pull request by abhishekakade**
**Description of PR**
Added `sitemap.xml` for better SEO and crawling.
Added sitemap to `robots.txt`.

**Note:** Mods with access to Google Analytics, etc of this website will have to actually submit this `sitemap.xml` file/url to [Google Search Console](https://support.google.com/webmasters/answer/7451001).

**Type of PR**
- [x] SEO

Closes #1110, #262

### CODE REVIEW

**Comment by tannakartikey** [comment]
@abhishekakade thanks for the PR.
Any way we can update the sitemap automatically?
If you have knowledge to do that would you like to update your PR?

**Comment by abhishekakade** [comment]
@tannakartikey, I tried a lot to automate it but with the complex routes in the app, it doesn't seem possible. I even tried taking the routes outside in a separate file but babel still threw a lot of errors on components. It only worked when I created a separate file just for paths and nothing else. But that will still make the process manual since someone has to update the paths in that file manually as they are updated in `App.js` so wouldn't it be better to just update them manually directly in `sitemap.xml` instead?

**Comment by tannakartikey** [comment]
@abhishekakade no problem. Thanks for trying.

**Comment by jeremyphilemon** [comment]
@abhishekakade Hey, we introduced a new state page recently. Would it be possible if you could add that to the sitemap as well?

Merging this for now, feel free to open a new PR addressing the above :)

**Pull request merged**
