### PR TITLE
#259: Added Alt tags for SEO Enchancment

### PR DESCRIPTION
**Pull request by arjunkesava**
This PR resolves this [issue](https://github.com/covid19india/covid19india-react/issues/259)

### CODE REVIEW

**Review by subhamkapoor360 — APPROVED** [review]

**Comment by arjunkesava** [comment]
@jeremyphilemon  please review and merge it

**Comment by JunaidBabu** [comment]
Please change all urls to https://www.covid19india.org/

**Comment by arjunkesava** [comment]
> https://www.covid19india.org/

Done @JunaidBabu, please check.

**Review by UdayMallikarjun — CHANGES_REQUESTED** [review]
In alt for logo we can remove the https/www part

**Comment by abhishekakade** [comment]
I had already made a PR for this with accessibility fixes included - #153 (which I myself asked to close) and #267

**Pull request merged**
