### PR TITLE
Feat: Support date range slider in Deep Dive

### LINKED ISSUE #813: Adding date range filter for the graphs.
**Is your feature request related to a problem? Please describe.**
We can add this to show graphs between two dates which will give more insight. 

**Describe the solution you'd like**
We will use pre built library to create date time range sliding filter. Based on range it will create a slice of data. All the graphs will be based on this sliced data.

**Additional context**
Screenshot 2020-04-08 23:52:24

### PR DESCRIPTION
**Pull request by ninjakx**
**Description of PR**
Added filter by date feature.

**Type of PR**

- [ ] Bugfix
- [X] New feature

**Relevant Issues**  
Fixes #813 

**Checklist**

- [X] Compiles and passes lint tests
- [X] Properly formatted
- [X] Tested on desktop
- [X] Tested on phone

**Screenshots**
ezgif com-video-to-gif (1)

### CODE REVIEW

**Comment by tannakartikey** [comment]
@ninjakx do we have to include jquery?

**Comment by Binu42** [comment]
@ninjakx Hey, this feature looks good and useful also but it's making page unresponsive below 779px width. this can be done also without including any additional packages.

**Comment by ninjakx** [comment]
@tannakartikey : Yeah have to otherwise won't be able to use that range thing which I have used. I tried some other way too but failed.

**Comment by ninjakx** [comment]
@Binu42 this is not because of using this. This was before that also, related to frontend css part.
Yes it can be done without additional package too. But I found UI part of it very clear and it's very easy to use. http://ionden.com/a/plugins/ion.rangeSlider/

**For mobile:**

Screenshot 2020-04-12 14:10:27

**Comment by jeremyphilemon** [comment]
Hey @ninjakx, thanks for the PR! We've unfortunately deprecated DeepDive at the moment, but we're working on a refactored version which will be out soon. So keep an eye out for it and PRs against that will be appreciated :)

**Pull request closed without merging**
