### PR TITLE
Ajax polling auto refresh

### PR DESCRIPTION
**Pull request by vinishanto**
Simple ajax polling to trigger a state update every 5 seconds(5000ms). added a hook for react interval

### CODE REVIEW

**Comment by abhishekkhandait** [comment]
refer #196

**Comment by vinishanto** [comment]
That's fine never mind. The issue is still open https://github.com/covid19india/covid19india-react/issues/178. I recommend link this and close the issue

**Comment by vinishanto** [comment]
This PR also covers other components on the home page that was missed in #196. This also includes the feature, that polling will stop when navigated to a different tab and I believe the ideal time for ajax polling is 5 secs.

**Comment by jeremyphilemon** [comment]
Hey this looks good, however, I think polling every 5secs might seem a little too overkill considering the api refreshes every nine-ten minutes. Could you change that value, squash your commits and rebase?

**Comment by dpnkrpl** [comment]
No need to refresh in every 5 seconds. 15 minutes should be enough I guess.

**Comment by jayantbh** [comment]
If the DB updates every 9-10 minutes, then I guess no need for a polling based auto-refresh at all.

Realistically no one has the tab open for 10 minutes. But I reckon the maintainers with access to analytics would know better.

I understand that a PR has been merged for updating every 10 minutes, but I'd like to know your thoughts nonetheless.

**Comment by shivendra-kumar** [comment]
Can't we use Server Sent Events for this instead of Ajax polling. Whenever there will be an update server will just push it to client so need of polling.

**Comment by jeremyphilemon** [comment]
Closing due to inactivity.

**Pull request closed without merging**
