### PR TITLE
correcting mapping of Gurgaon, Jhunjhunu, Gulbarga, Mehsana, gautam b…

### PR DESCRIPTION
**Pull request by anuragjain**
Corrected mapping of Gurgaon, Jhunjhunu, Gulbarga, Mehsana, gautam buddha nagar so that proper data gets rendered on district maps

### CODE REVIEW

**Comment by JunaidBabu** [comment]
@guneetnarula could you please review this?

**Comment by JunaidBabu** [comment]
@anuragjain sorry I merged another PR with karnataka first. Could you fix the merge conflict?

And also, how did you match the names? Are you following the standard names used in the sheets?
https://docs.google.com/spreadsheets/d/e/2PACX-1vSc_2y5N0I67wDU38DjDh35IZSIS30rQf7_NYZhtYYGU1jJYT6_kDx4YpF-qw0LSlGsBYP8pqM_a1Pd/pubhtml

**Comment by anuragjain** [comment]
@JunaidBabu I have resolved the conflicts.
Yes I'm using names from sheet itself, have verified the number coming correctly in preview as well.

**Comment by JunaidBabu** [comment]
Merging without verifying everything.

**Comment by guneetnarula** [comment]
A reference list for all 727 district names with states is ready. This will be used in the data collection and in the JSONs. Should take care of #301 as well. Will create an issue + PR soon

**Pull request merged**
