### PR TITLE
feature:added WhatsApp share button

### PR DESCRIPTION
**Pull request by saquibkhan**
**Description of PR**
Added WhatsApp Share button, only for mobile
**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Before -->
image

After -->
image

WhatsApp Shared Message -->
image

### CODE REVIEW

**Comment by saquibkhan** [comment]
@jeremyphilemon @JunaidBabu Please review and merge

**Comment by denvamsi** [comment]
This isnt working, Can you please check ?

**Comment by saquibkhan** [comment]
@denvamsi I checked just now and its working? Please note that this icon is only visible on Mobile.

Which mobile did you use for testing, can you provide some more details?

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! As mentioned in the [contributing](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) guide, please have an issue filed first, have it accepted, then assigned to you before submitting a PR :)

This will help us discuss any changes/requirements before work is done on it!

**Pull request closed without merging**
