### PR TITLE
Make maps more responsive

### LINKED ISSUE #57: Legend in the map and the data in the map seems different
COVID-19 Tracker   India -legend

The legend used  in the map for showing the  color  for corresponding data(Kerala) seems different as seen in the screenshot

### LINKED ISSUE #504: Map color not as per count in Goa
**Describe the bug**
Color of North Goa map is not as per the map color chart. 

**To Reproduce**

1. Go to https://www.covid19india.org/
2. Click on Goa map
3. See error : As per the map color chart with the count of 3, the color of North Goa map is showing red.

**Expected behavior**
As per the map color chart with the count of 3, the color should be orange.

**Screenshots**
GoaCovid

**Desktop (please complete the following information):**

- OS : Windows 10
- Browser : Chrome
- Version : 80.0

**Smartphone (please complete the following information):**
NA

### LINKED ISSUE #785: 'Districts Unknown ...' text overlaps with legend
**To Reproduce**
On phone, 
1. Go to the India map
2. Double tap Madhya Pradesh to open district view

**Screenshots**
image

### LINKED ISSUE #1045: Colour coding not working
Colour coding given for severity for state is not getting updated with scale change

1. Go to  maps -> kerala
2. Kerala should be in severity scale 1 but shows severity level 2

**Expected behavior**
Kerala to be on least severity 

**Screenshots**
Added

**Desktop (please complete the following information):**

- OS:  windows
- Browser chrome
- Version latest

**Smartphone (please complete the following information):**

- Device: iphone se
- OS: ios 13
- Browser chrome
- Version latest

**Additional context**
AF39F330-E026-43B0-8C8E-51A94DEE303A

### PR DESCRIPTION
**Pull request by shuklaayush**
**Description of PR**
This PR will
- Increase map sizes by making them span entire width of the section 
- Cache maps which have previously been loaded. Toggle the display style of extra maps to 'none' when they're out of view, instead of removing them from SVG
- Add zoom animation to transitions between country and state maps
- Move legend below map. Use d3-scale instead of manual interpolation
- Move the district information text above the map
- Sneak in uniform scaling disabled by default

**PS :** I'm aware that animations stutter on Chromium-based browsers on Android. This seems to me like a bug in how SVGs are rendered in Chromium. The behaviour's better in Chrome Canary. Since I don't have the slightest idea as to how debugging is done in Chrome/Android, any help is much appreciated.

**Type of PR**

- [x] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #57 (finally) , fixes #504, fixes #785 (somewhat), fixes #1045 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Peek 2020-04-10 13-13

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
mhmmmmmmmmmm

**Comment by shuklaayush** [comment]
~~And now I have a conflict.~~ Rebased.

**Comment by shuklaayush** [comment]
Superseded by #1133

**Pull request closed without merging**
