### PR TITLE
Issue#743 - Dark Mode (without palette changes)

### LINKED ISSUE #743: A dark mode based on local clock
**Is your feature request related to a problem? Please describe.**
During night time, it might induce eye strain. 

**Describe the solution you'd like**
A dark mode that toggles automatically with system time. 

**Describe alternatives you've considered**
An alternative would be to continuously alter the intensity of the background as per time. But a dark mode might be preferred 

**Additional context**

### PR DESCRIPTION
**Pull request by vandanachandola**
**Description of PR**
Introduced dark mode toggle button. Checks `prefers-color-scheme` preference for user or `darkMode` value in localStorage and sets theme accordingly. Palette changes are not included in this PR.

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #743 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

**Screenshots**

### CODE REVIEW

**Comment by parthbhide** [comment]
Dark mode toggle button overlaps the Navigation toggle button.
Also when navigation is toggled , menu isn't in dark mode. 

Screenshot_2020-04-14-11-34-23-469_com android chrome




Screenshot_2020-04-14-11-36-34-208_com android chrome

**Comment by vandanachandola** [comment]
@parthbhide My bad! Thanks for pointing out these issues.. I'll work on them tonight.

**Comment by akhiltulluri** [comment]
This looks great! Why not add some text around the button describing what it does?
And I feel like the text showing advices like "Lockdown is LOCKDOWN" part is kinda unreadable when on dark mode.  Or is it something with the palette changes?👀

**Comment by vandanachandola** [comment]
> This looks great! Why not add some text around the button describing what it does?
> And I feel like the text showing advices like "Lockdown is LOCKDOWN" part is kinda unreadable when on dark mode. Or is it something with the palette changes?👀

@officialakhil thank you.. i was thinking maybe icons or Unicode symbols (something like ☀ and ☽) instead of text.  Color palette is already in progress I believe, so I didn't include changes related to that, like banner text color.

**Comment by akhiltulluri** [comment]
@vandanachandola yea icons like that sounds cool. 👍

**Comment by vandanachandola** [comment]
This PR is no longer valid. Go to this [draft PR](https://github.com/covid19india/covid19india-react/pull/1234) to check dark-mode changes.

**Pull request closed without merging**
