### PR TITLE
Feature: Added mortality 

### PR DESCRIPTION
**Pull request by surinder83singh**
**Description of PR**
DEATH percentage column in table

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests 
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Screenshot 2020-04-10 at 12 33 09 AM

### CODE REVIEW

**Comment by bee-rickey** [comment]
May have to rename Death percentage as Mortality rate. Rest looks good.

**Comment by surinder83singh** [comment]
column title updated

**Review by jeremyphilemon — CHANGES_REQUESTED** [review]
Hey, we've decided not to include this as a column. Could you have this added in the state page in `stats-secondary`?

**Comment by saurabhsharma1976** [comment]
well done to all involved! I had this in mind as an unfortunate but real outcome measure. Next step cud b to statistically predict. Know margin of error. we can use stats conf levels and keep restricted. Any one to prioritise. With over 20 yrs of corp biz prcess & six sigma experience, happy to collaborate. Nube on tech though but srong on logic. lemme know pls

**Comment by jeremyphilemon** [comment]
Closing due to inactivity.

**Comment by saurabhsharma1976** [comment]
Sorry naive question - is it deployed as connot see online right now?

**Comment by surinder83singh** [comment]
what is the use of data if we cant compare it with difference sources/states ?

**Pull request closed without merging**
