### PR TITLE
Serviceworker to make webapp as Progressive & offline page

### PR DESCRIPTION
**Pull request by dharshakch97**
**Description of PR**

In this pull request, I've added serviceworker.js file in public to make this website as a progressive web app(PWA).
Adding to this, offline.html is added which appears when there is no network.

**Checklist**

- [ ] Compiled and tested
- [ ] Properly formatted
- [ ] Tested on desktop
- [ ] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Comment by shuklaayush** [comment]
It's already a PWA. Follow the contribution guidelines and open an issue first before you make a PR

**Comment by dharshakch97** [comment]
@shuklaayush but I couldn't see any '+' icon on the url bar to add it on my system, when I visited covid19india.org.

**Comment by shuklaayush** [comment]
That's probably a separate issue. It shows up on mine
image

**Comment by dharshakch97** [comment]
Ok! I'll see it. I've used service worker to make a webapp progressive. Is there other way to make it?

**Comment by shuklaayush** [comment]
These might help
https://github.com/covid19india/covid19india-react/blob/49fc70f974cc8caec5859bfc518e515be4247f3d/src/index.js#L17

https://github.com/covid19india/covid19india-react/blob/master/src/serviceWorker.js

**Pull request closed without merging**
