### PR TITLE
Increased the size of the main logo. Issue - 473

### LINKED ISSUE #473: Logo on "title bar"
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
**The logo seems too tiny when opened in desktop site,though its not so clear in phone either**

**Describe the solution you'd like**
The same logo can be enlarged (and/or) made colourful

### PR DESCRIPTION
**Pull request by saranshgupta1995**
**Description of PR**

**Type of PR**
- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #473

**Checklist**
- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
After proposed changes
image
image

### CODE REVIEW

**Comment by saranshgupta1995** [comment]
@JunaidBabu @sudevschiz, please merge if appropriate.

**Comment by saranshgupta1995** [comment]
@jeremyphilemon

**Comment by jeremyphilemon** [comment]
Hey thanks for the PR! As mentioned in the [contributing](https://github.com/covid19india/covid19india-react/blob/master/CONTRIBUTING.md) guide, please have an issue filed first, have it accepted, then assigned to you before submitting a PR :)

This will help us discuss any changes/requirements before work is done on it!

**Comment by saranshgupta1995** [comment]
Hi @jeremyphilemon, The issue has been raised already by another user. This PR solves the issue #473 as mentioned in the description.

**Comment by jeremyphilemon** [comment]
Yes I agree, but the issue wasn't moved to "available". Feel free assign yourself to issues labelled "available" and submit PRs :)

Don't be discouraged, it's hard to maintain changes when we receive PRs for unaccepted issues. I'll definitely keep an eye out if you want to assign yourself to an available issue!

**Pull request closed without merging**
