### PR TITLE
Page stutters on transitioning to new page #1239

### LINKED ISSUE #1239: Page stutters on transitioning to new page
**Describe the bug**
Page stutters on going back to the home page. Or maybe just stutters between switching to a new page. (Maybe not visible in the gif below)

ezgif-7-b547074b42e0-2

**To Reproduce**
Navigate to any page, and head back to home.

**Expected behavior**
The page shouldn't stutter.

### PR DESCRIPTION
**Pull request by lakshmi14**
**Description of PR**

**Type of PR**

- [x] Bugfix

**Relevant Issues**  
Fixes #1239 

**Checklist**

- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

### CODE REVIEW

**Comment by strikertanmay** [comment]
Can u please check once when we return to the home page, India map is not visible
s

**Comment by strikertanmay** [comment]
Please check once that after returns to the home page, the india map is not visible.
s

**Comment by lakshmi14** [comment]
Hi Tanmay,
Can you please let me know the steps to reproduce. I am unable to reproduce. working fine in the testing site, cross-checked both in desktop and mobile. Thanks in advance!

**Comment by strikertanmay** [comment]
> Hi Tanmay,
> Can you please let me know the steps to reproduce. I am unable to reproduce. working fine in the testing site, cross-checked both in desktop and mobile. Thanks in advance!

I hope this will helps u. I checked many times. This occurs randomly
COVID-19 Tracker _ India

**Comment by lakshmi14** [comment]
Hi.. May i know the url you are testing with and which browser are you testing this with ?

I have tested in Chrome,edge ,IE and mobile. Thanks

**Comment by strikertanmay** [comment]
> Hi.. May i know the url you are testing with and which browser are you testing this with ?
> 
> I have tested in Chrome,edge ,IE and mobile. Thanks

 https://covid19india-react-git-fork-lakshmi14-newbranch.covid19india.now.sh

**Comment by jeremyphilemon** [comment]
@lakshmi14 Looks good to me! Thanks :)

@strikertanmay Looks like the map not showing may not be related to the changes made in this PR.

**Pull request merged**
