### PR TITLE
MythBuster Tab

### PR DESCRIPTION
**Pull request by sagarv1997**
Referencing #190 Added a Myth Buster Tab.

It is a stack of image card which can be swiped. Referenced [React Spring](https://github.com/react-spring)'s card example

Desktop:
image

Mobile:
image

### CODE REVIEW

**Comment by sudevschiz** [comment]
Whoah. Have a look @jeremyphilemon @JunaidBabu 

@sagarv1997 What can be our policy to easily update the cards. 

Let me show this to the social and design team too, so that we make sure there is design parity.

**Comment by sagarv1997** [comment]
> Whoah. Have a look @jeremyphilemon @JunaidBabu
> 
> @sagarv1997 What can be our policy to easily update the cards.
> 
> Let me show this to the social and design team too, so that we make sure there is design parity.

It can easily be edited by making changes in **#card > div > div**, If more information needs to be added in the cards like sources, or any other text, it can be added in card.js, I did add source information, but have commented it in the code.

**Comment by jeremyphilemon** [comment]
@sudevschiz Looks good to me!

**Comment by sudevschiz** [comment]
@sagarv1997 The card links to external sources? Worried about what happens if the link breaks

**Comment by sagarv1997** [comment]
> @sagarv1997 The card links to external sources? Worried about what happens if the link breaks

Links are from the official tweets from the MyGov, I doubt they will ever remove it

**Comment by sagarv1997** [comment]
> @sagarv1997 The card links to external sources? Worried about what happens if the link breaks

We can even download and upload the images in some free image hosting website (imgur) and can give the source and credits in the cards

**Comment by sagarv1997** [comment]
@sudevschiz Any updates?

**Comment by JunaidBabu** [comment]
Will consider later. Closing for now.

**Pull request closed without merging**
