### PR TITLE
Style: Add padding to DeepDive charts

### LINKED ISSUE #1202: Padding and Margin issue on the Deep Dive Page on Desktop
**Describe the bug**

The Deep Dive Page overlaps with the left Nav bar.

**To Reproduce**

1. Go to 'Deep Dive'
4. Notice the overlap of the left most boxes.

**Screenshots**
deepdive_issue

**Expected behavior**
Proper Margin and Padding should be maintained. 
image

### PR DESCRIPTION
**Pull request by Binu42**
**Description of PR**
* Not maintaining proper padding by card container.
* styled card for better UI Look.

**Type of PR**

- [x] Bugfix

**Relevant Issues**
Fixes #1202 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
#### Before Fix....
Screenshot from 2020-04-17 04-06-34
<br>

#### After Fix...
Screenshot from 2020-04-17 04-08-31

### CODE REVIEW

**Review by s-naveen — APPROVED** [review]

**Comment by spraveenofficial** [comment]
Binu can you please send me the source code? Of this stats :(

**Comment by Binu42** [comment]
> Binu can you please send me the source code? Of this stats :(

@spraveenofficial source code for this branch is here https://github.com/Binu42/covid19india-react/tree/deepDive or you can use git cmd to clone it  ``` git clone --single-branch --branch deepDive https://github.com/Binu42/covid19india-react.git```

**Comment by Binu42** [comment]
@jeremyphilemon @sudevschiz these changes are approved by @s-naveen 2 days ago can you guys, look at it and merge it.

**Comment by jeremyphilemon** [comment]
We went ahead and used #1082 for the UI and card design, so closing this. Thanks anyway :)

**Pull request closed without merging**
