### PR TITLE
Replaced ES6 Map with lodash map for performance

### PR DESCRIPTION
**Pull request by keshavbiswa**
Refactor:

Lodash will enhance performance as the app scales.
Replaced all ES6 maps to lodash maps.

### CODE REVIEW

**Comment by crup** [comment]
`import _ from 'lodash';`

I don't think this will treeshake properly. If I am right, this PR is bloating the bundle by 30kb+

Rather try `import map from from "loadsh/map"`

https://www.covid19india.org/
image

https://covid19india-react-git-fork-keshavbiswa-integrate-lodash.covid19india.now.sh/
image

**Comment by vramana** [comment]
> Lodash will enhance performance as the app scales.
> Replaced all ES6 maps to lodash maps.

A lot of performance has gone into Array.prototype.map performance over the last few years. How much difference is does it make? Can you run some benchmarks and see if there is percievable difference? If it's 10ms vs 15ms It's not that much. But 1sec vs 3sec that's a much bigger difference. The general rule to make any performance improvements is measure the thing you want to improve.

**Comment by jeremyphilemon** [comment]
Hey, this is an interesting PR! Honestly I don't see much impact on switching to lodash for very minimal performance increases, given the arrays are not that large. 

If you could run some benchmark tests and share the results, you can prolly change my mind :)

**Comment by keshavbiswa** [comment]
Now that I think about it. Doesn't really make any difference and the data is always going to remain small so doesn't have any impact. Going to close this pr now.

**Pull request closed without merging**
