### PR TITLE
localization support

### LINKED ISSUE #98: Localization for the app
Is there any plan to allow localization? We can get the po files translated quickly to different languages.

### PR DESCRIPTION
**Pull request by harshzalavadiya**
Closes #98, #21 

As of now I have added some mostly used languages more can be added on demand reference https://en.wikipedia.org/wiki/Languages_of_India

### Languages added 
- Hindi
- English
- Bengali
- Marathi
- Telugu
- Tamil
- Gujarati
- Urdu
- Kannada
- Odia
- Malayalam
- Punjabi

p.s. current translations are done using google translate (google sheet's `=GOOGLETRANSLATE()`) so it's not going to be perfect can be improved with community support.

as most of the components had single quotes, I have added `.editorconfig` so editor can automatically detact that it's in single quotes

### CODE REVIEW

**Comment by abhishekkhandait** [comment]
IMHO translation for FAQs and banner is a must and it seems to be missing

**Comment by harshzalavadiya** [comment]
Yes, @abhishekkhandait translations and banner is coming from JSON api back-end has to support translations or has to be moved to translation files

**Update** as of now to get translated JSON I have added `lang` query param to json calls

**Comment by harshzalavadiya** [comment]
Edit just now looked at https://github.com/covid19india/api apparently it's static json and seems to be coming from google sheets

one possible solution can be adding columns with `question-en`, `answer-en` etc. and generating multiple FAQ files like `faq-en.json`

being google sheet you can take advantage of `GOOGLETRANSLATE` function let it do it automatically

**Comment by harshzalavadiya** [comment]
Well, I have resolved conflicts more then 3-4 times to keep branch up to date and it keeps on happening plus not sure if this is going to merge.
If it is going to merge then let me know I'll try to resolve conflicts otherwise I won't be pushing updates on this PR from now on as there's no response from core devs

IMHO as of now everyone is pushing commits and not following any formatting guidelines it will be worthwhile to add opinionated formatter like prettier so merge conflicts can be very minimal

Anyways thank you all devs of this repo this is an amazing project keep up the good work

**Comment by andante-9** [comment]
Do you need help with this? I can pick up some of the slack

**Comment by s-naveen** [comment]
> Well, I have resolved conflicts more then 3-4 times to keep branch up to date and it keeps on happening plus not sure if this is going to merge.
> If it is going to merge then let me know I'll try to resolve conflicts otherwise I won't be pushing updates on this PR from now on as there's no response from core devs
> 
> IMHO as of now everyone is pushing commits and not following any formatting guidelines it will be worthwhile to add opinionated formatter like prettier so merge conflicts can be very minimal
> 
> Anyways thank you all devs of this repo this is an amazing project keep up the good work

@harshzalavadiya you should rebase over upstream and force push instead of merging that would keep commits clean.

**Comment by harshzalavadiya** [comment]
@andante-9 I don't have any issues working on this PR, as of now there's nothing to be done as there's no input from the project maintainers. seems this is low priority as of now.

@s-naveen you might be right but I am no expert in git, and this PR is modifying most off the files and due to that it's generating conflict everytime, plus looks like each maintainers has it's own way of formatting files and due to that it just creates unnecessary diff that can easily be avoided.

**update**: there's already a PR adding eslint and prettier for this https://github.com/covid19india/covid19india-react/pull/192

**Comment by jeremyphilemon** [comment]
@harshzalavadiya hey really sorry, the devs didn't really expect a lot of incoming PRs at the time of release so we didn't think about settings up the style guidelines since it was only a very few people at first.

I'm closing this right now since I believe we've had major revisions to the codebase since this was opened – which I apologize due to the lack of time – but feel free to work on this again! 

I've assigned you to  #21 exclusively, I'll keep an eye out for your PR.

**Comment by harshzalavadiya** [comment]
Sure I get it I'll submit an PR tomorrow

**Pull request closed without merging**
