### PR TITLE
Added Activity Center to see history of cases throughout the day 

### LINKED ISSUE #292: Activity Center needed to see history of cases throughout the day
**Is your feature request related to a problem? Please describe.**
Whenever a new case coming in I cannot understand where it happened for  example I can see 1 minute ago updated and I can see the numbers but they are not clear enough to give me a clear picture where it happened without going into the db

**Describe the solution you'd like**
if there is a activity center where it can be mentioned something like this : "A new Confirmed case in the state of Maharashtra"
or "YaY!!! A new patient recovered from Covid-19"
then it will be helpful
**Describe alternatives you've considered**
The Other Alternative can be notifications but people can miss notifications and it's annoying also...rather an activity center will keep a history of events which I can come back to by the end of day and have a look.

### PR DESCRIPTION
**Pull request by faisal3389**
**Description of PR**
Added Activity Center to see the history of cases throughout the day. Whenever a new case coming in the day the history is added to the activity center.

**Type of PR**

- [ ] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #292

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Screenshot 2020-04-06 at 1 57 08 PM
Screenshot 2020-04-06 at 1 57 37 PM

### CODE REVIEW

**Comment by denvamsi** [comment]
Looks super cool and please match the exact font and make some style tweaks so it will look good :) Instead add a button on top and make it open in a popup :)

**Comment by faisal3389** [comment]
> Looks super cool and please match the exact font and make some style tweaks so it will look good :) Instead add a button on top and make it open in a popup :)

sure, I have updated to use the same font-color and font-weight. Please let me know if this is better.

**Comment by denvamsi** [comment]
image
Why not trying something like this ? Currently it looks good but this tweak can make it more better :)

**Comment by jeremyphilemon** [comment]
Thank you for the PR :)

**Pull request merged**
