### PR TITLE
Add: Chart for deceased by age

### PR DESCRIPTION
**Pull request by vibvibgyor**
**Description of PR**

Added histogram for deceased by age.

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Selection_032

### CODE REVIEW

**Comment by bee-rickey** [comment]
I feel this would a misleading chart since the data set is small.

**Comment by vibvibgyor** [comment]
The patient age chart has sample size of 2,344 patients out of 43,562 patients, which is around 5.3%. Now, when we compare sample size for deceased which is 44 out of 1,401 total deceased, this is around 3.3%. Even, the first chart doesn't give any significant results. I think, we should also remove the first chart. What do you think? @bee-rickey @shuklaayush

**Comment by bee-rickey** [comment]
> The patient age chart has sample size of 2,344 patients out of 43,562 patients, which is around 5.3%. Now, when we compare sample size for deceased which is 44 out of 1,401 total deceased, this is around 3.3%. Even, the first chart doesn't give any significant results. I think, we should also remove the first chart. What do you think? @bee-rickey @shuklaayush

I think we should remove the other chart as well. +1 on that.

**Comment by vibvibgyor** [comment]
Yeah. Please check #1785

**Comment by shuklaayush** [comment]
Seems like this PR is obsolete now since deep-dive was deprecated. Closing

**Pull request closed without merging**
