### PR TITLE
fixes #1944 flexbox width size fix

### LINKED ISSUE #1944: Tap on Maharashtra on India map redirects to karnataka
**Describe the bug**
Tapping on the Maharashtra on the India map redirects to the Benguluru urban in Karnataka

**To Reproduce**

1. Go to 'India map section'
2. Click on Maharashtra
3. See error

**Expected behavior**
Maharashtra state page was expected to be displayed.
But it is directing to the Bengaluru urban district in Karnataka

**Screenshots**
Chrome

**Smartphone (please complete the following information):**

- Device: [Redmi Note 5 pro]
- OS: [Android 9.0]
- Browser [Google Chrome]

### PR DESCRIPTION
**Pull request by mohammedsrehan**
**Description of PR**

A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange feedback, and merge!

**Relevant Issues**  
Fixes #1944 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Comment by bee-rickey** [comment]
What's this change? And why?

**Comment by mohammedsrehan** [comment]
Was trying to fix the issue  #1944

**Comment by mohammedsrehan** [comment]
The issue still exists and is not fixed
Its very annoying to use the page with this issue @bee-rickey

**Comment by shuklaayush** [comment]
Seems to be obsolete now

**Pull request closed without merging**
