### PR TITLE
PWA - Add to Home Screen Support

### PR DESCRIPTION
**Pull request by vrajeshkanna**
Adds PWA capability to the website. Addresses #78

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Appreciate this! Have questions on this, @vrajeshkanna do we need to be concerned about cache versions not updating after a change in the website's codebase?

**Comment by vrajeshkanna** [comment]
@jeremyphilemon I haven't added any files to cache yet. Just enabled the service worker.

**Comment by vrajeshkanna** [comment]
PR #133 is better. Please pick that @jeremyphilemon

**Comment by kdnanmaga** [comment]
I am still not getting the Add to Home Screen Pop-Up. I am attaching a report from Google's lighthouse tool for things that need to be fixed to get the PWA working.
Workspace 1_013

**Pull request closed without merging**
