### PR TITLE
District level graph exploration

### PR DESCRIPTION
**Pull request by manojVivek**
This PR allows district level exploration for 19 states. I'm working on filling in the remaining. 

Screenscast:

district-level-map

### CODE REVIEW

**Comment by JunaidBabu** [comment]
@manojVivek amazing work.

Are some states missing? Like Telangana?

**Comment by JunaidBabu** [comment]
Also, tapping on a state is messing up the graph below it

**Comment by sangamesh1439** [comment]
@manojVivek : In desktop when we move mouse over it will show state wise analysis. But in mobile phone we have to single click on state to see the state details. As per your changes, You need a single click on state to switch to district level. Have you tested this test case in mobile device ?

**Comment by manojVivek** [comment]
> @manojVivek amazing work.
> 
> Are some states missing? Like Telangana?

@JunaidBabu  GeoData missing states are Telangana, Andhra, JK and Ladakh. Other are available I'm yet to add them to the PR.

**Comment by manojVivek** [comment]
> Also, tapping on a state is messing up the graph below it

Added a fix for this.

**Comment by manojVivek** [comment]
> @manojVivek : In desktop when we move mouse over it will show state wise analysis. But in mobile phone we have to single click on state to see the state details. As per your changes, You need a single click on state to switch to district level. Have you tested this test case in mobile device ?

@sangamesh1439 d3 has in-built handling this. In mobile this is how it works: 

1. First tap shown the state details(like hover on desktop).
2. Second tap on the same state opens the district level details for that state.

**Comment by manojVivek** [comment]
@jeremyphilemon @JunaidBabu I have fixed all the issues and added all states except Telangana, Andhra, JK and Ladakh. This is in a stable state now, let me know.

**Comment by abhishekkhandait** [comment]
@manojVivek there seems to be some inaccuracy in data. For ex. Odisha shows 2 active cases but district-level graph shows nothing.

**Comment by JunaidBabu** [comment]
I think it's because some cases are under "unknown". 

This needs to be displayed somehow. Maybe a bubble outside the map or mentioned it clearly when tapped onna state. This can confuse people and spread the wrong idea.

**Comment by manojVivek** [comment]
@abhishekkhandait @JunaidBabu Added an indication for unidentified districts. Screenshot below:
Screenshot 2020-03-26 at 9 51 59 AM

**Comment by khaaba** [comment]
Manipur district, Imphal West where the infection is reported, has been shown **overlapped with the present Jiribam District** (newly created District though it was called Imphal West before). It seems like map is created with the old undivided district boundaries (_**9 districts**_). At present, Manipur has a total of **16 districts**!

**Comment by neel112358** [comment]
@khaaba @manojVivek It seems to be a problem with the json file you might be using
Here's a file where districts are provided correctly. 
https://github.com/deldersveld/topojson/blob/master/countries/india/india-districts.json

Also, the problem is not just for Manipur but for Gujarat as well, where there are 14 cases and 1 death but it shows 0 on the preview. I think it looks like a string matching issue. Graph has "AHMADABAD" but you might be comparing it with "AHMEDABAD"

**Comment by neel112358** [comment]
@khaaba  @manojVivek Same being the issue with "KACHCHH" and "KUTCH" which actually has 1 case

**Comment by neel112358** [comment]
As I see, the HTML is not that well structured for this but clicking on a state on the map should event-trigger the highlighted button so that both views are seen.

**Comment by manojVivek** [comment]
> @khaaba @manojVivek It seems to be a problem with the json file you might be using
> Here's a file where districts are provided correctly.
> https://github.com/deldersveld/topojson/blob/master/countries/india/india-districts.json
> 
> Also, the problem is not just for Manipur but for Gujarat as well, where there are 14 cases and 1 death but it shows 0 on the preview. I think it looks like a string matching issue. Graph has "AHMADABAD" but you might be comparing it with "AHMEDABAD"

@neel112358 Thanks for identifying it. I'll run a script to compare the district names and fix them.

**Comment by sudevschiz** [comment]
@manojVivek Amazing work!
Can you have a look at this one issue : 
When the number of cases are quite low, the scales come out to be 1-0,1-0 etc. Ideally, this should be just a single value if the number of cases are <10 or so?


image

**Comment by manojVivek** [comment]
@sudevschiz I have fixed the legends for states without any cases. 
Screenshot:
Screenshot 2020-03-26 at 10 25 58 PM

**Comment by manojVivek** [comment]
@JunaidBabu @jeremyphilemon Guys, let me know if there is any more things we need for merging this in.

It is too hard to keep up(merging conflicts) with the changes happening on the `master` as this PR involves a major refactoring on the `Choropleth` component. :)

**Comment by khaaba** [comment]
> @JunaidBabu @jeremyphilemon Guys, let me know if there is any more things we need for merging this in.
> 
> It is too hard to keep up(merging conflicts) with the changes happening on the `master` as this PR involves a major refactoring on the `Choropleth` component. :)

@manojVivek Thanks for the update. However, Manipur map has the same issue still (old 9 districts are shown in the current map). Sorry, I couldn't help you with the coding. Seems like @neel112358 is right but his link still misses few new districts. I am attaching herewith two maps for comparison purpose only. Other one has the correct districts in the state.
NewMap2

This one below has the correct number of districts (16 Nos.) with the location of the district, **Imphal West**, **_in the right place_**.
NewMap

This formatted json file could be used as updated districts:
[https://github.com/sab99r/Indian-States-And-Districts](https://github.com/sab99r/Indian-States-And-Districts )

**Comment by abhishekkhandait** [comment]
@manojVivek Table is getting duplicated.

ss
Screenshot 2020-03-26 at 11 58 19 PM

Edit: correct screenshot attached

**Comment by manojVivek** [comment]
> @manojVivek Table is getting duplicated.
> 
> ss
> Screenshot 2020-03-26 at 11 58 19 PM
> 
> Edit: correct screenshot attached

@abhishekkhandait My bad, fixed it now.

**Comment by khaaba** [comment]
This file could be used for correct districts (729 all in all at present):
https://github.com/sab99r/Indian-States-And-Districts/blob/master/states-and-districts.json

**Comment by neel112358** [comment]
@manojVivek Here's a taluka level map as well. If there are any inconsistencies, this can help resolve those (cases like J&K, Ladakh, Telangana etc.)
https://github.com/geohacker/india/blob/master/taluk/india_taluk.geojson

**Comment by khaaba** [comment]
> @manojVivek Here's a taluka level map as well. If there are any inconsistencies, this can help resolve those (cases like J&K, Ladakh, Telangana etc.)
> https://github.com/geohacker/india/blob/master/taluk/india_taluk.geojson

@neel112358, I would suggest that we have first the updated districts correctly in all the Sates and UTs. Taluka level is deeper boundaries beyond the districts.

**Comment by neel112358** [comment]
@khaaba I am not talking about going into taluka level. In parts of the North East and J&K, talukas, itself are the districts, so extracting that geojson part would be simpler for @manojVivek  to do than to do it manually

**Comment by neel112358** [comment]
@manojVivek  Here are a few cases, but except that there are still a lot where the legend hasn't been fixed. Seems to be a small conditional bug. 
@khaaba And is it okay that the map is overlapping the "District Unidentfied Cases" label?

**Comment by manojVivek** [comment]
@neel112358 The problem with legends is fixed, it was happening when the max confirmed cases are less than the legend cells count. 

Fixed the map overlapping on the information panels, to most part, by adjusting the scale factors but it is not a blocker as the map will be still interactable without hiding the info.

**Comment by khaaba** [comment]
> @neel112358 The problem with legends is fixed, it was happening when the max confirmed cases are less than the legend cells count.
> 
> Fixed the map overlapping on the information panels, to most part, by adjusting the scale factors but it is not a blocker as the map will be still interactable without hiding the info.

@manojVivek Please fix the _districts correctly_ too as pointed earlier!

**Comment by manojVivek** [comment]
> > @neel112358 The problem with legends is fixed, it was happening when the max confirmed cases are less than the legend cells count.
> > Fixed the map overlapping on the information panels, to most part, by adjusting the scale factors but it is not a blocker as the map will be still interactable without hiding the info.
> 
> @manojVivek Please fix the _districts correctly_ too as pointed earlier!

@khaaba I will need some help there. I couldn't find any state geoData out there that we can use. 
The one that is mentioned above is for Taluks and it needs some map processing expertise to convert it to suit our use-case and I don't have that expertise. :) 

Would appreciate any help on this.

**Comment by khaaba** [comment]
> > > @neel112358 The problem with legends is fixed, it was happening when the max confirmed cases are less than the legend cells count.
> > > Fixed the map overlapping on the information panels, to most part, by adjusting the scale factors but it is not a blocker as the map will be still interactable without hiding the info.
> > 
> > 
> > @manojVivek Please fix the _districts correctly_ too as pointed earlier!
> 
> @khaaba I will need some help there. I couldn't find any state geoData out there that we can use.
> The one that is mentioned above is for Taluks and it needs some map processing expertise to convert it to suit our use-case and I don't have that expertise. :)
> 
> Would appreciate any help on this.

@manojVivek as pointed out earlier [here](https://github.com/covid19india/covid19india-react/issues/13#issuecomment-603053553) by @jeremyphilemon. Hope you can use their geoData. Screenshot is at [https://github.com/guneetnarula/covid19-in/blob/master/screenshot-fieldmaps-in-1584404053753.png] (https://github.com/guneetnarula/covid19-in/blob/master/screenshot-fieldmaps-in-1584404053753.png). Looking into @guneetnarula's page: I found this [https://github.com/guneetnarula/covid19-in/tree/master/js](https://github.com/guneetnarula/covid19-in/tree/master/js) an India map with complete 729 districts. His state boundaries may be ignored like in this page (the page you are working on)

**Comment by khaaba** [comment]
@manojVivek I am not a python/javascript programmer, but let me know if there is anything whether it is manual cleaning like I can do from my end to help fix this, please let me know :)

**Comment by jeremyphilemon** [comment]
@manojVivek this definitely looks good, could you rebase this please?

**Comment by manojVivek** [comment]
> @manojVivek this definitely looks good, could you rebase this please?

@jeremyphilemon Rebase done 👍

**Comment by jeremyphilemon** [comment]
@manojVivek honestly loved this PR! Great stuff :)

**Comment by khaaba** [comment]
Good One! However, Manipur map is with old district layout: 9 districts instead of the present 16 districts. That way, Imphal West districts which is supposed to be somewhere below the Imphal East in the middle of the state's map is seen on the WESTERN side of the State!

edit: word correction!

**Comment by neel112358** [comment]
@manojVivek  I think it looks like a string matching issue again when hovering over district. Table has "AHMADABAD" but you might be comparing it with "AHMEDABAD"
Same being the issue with "KACHCHH" and "KUTCH"

**Comment by guneetnarula** [comment]
We are going to maintain district names here -> https://docs.google.com/spreadsheets/d/1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk/edit#gid=1207378023

**Pull request merged**
