### PR TITLE
FIX:: Bugfix for Tooltip overflow

### LINKED ISSUE #2076: Overflow problem when tooltip is open in state page in mobile
**Describe the bug**
Page overflow when tooltip is opened in state page in mobile

**To Reproduce**
Steps to reproduce the behavior: (mobile)

1. Go to state page
2. Tap on tooltip icon present in right cards
3. Notice the issue

**Expected behavior**
Should not overflow

**Screenshots**
Screenshot_20200607-203139
Screenshot_20200607-202238

### PR DESCRIPTION
**Pull request by sirdarthvader**
**Description of PR**

This PR is against the issue number #2076 

The issue was with the default position of the tooltip, while it was not an issue on desktop, for mobile devices, tooltip created this extra space in the body of the page.

So I have added a conditional style object for tooltip element basis the viewport size of the device. If it's a mobile device tooltip element would have added top and right CSS attributes keeping it overflowing from viewport.

Introduced a new custom hook function called located in useViewPort.js under the hooks folder. 

All the proposed changes will have an effect only on devices smaller or equal to 480px in width.

**Relevant Issues**  
Fixes #2076 

**Checklist**

- [x] Compiles and passes lint tests

- [x] Properly formatted

- [x] Tested on desktop

- [x] Tested on phone

**Screenshots**

Add relevant screenshots here
As seen on production

Screenshot 2020-07-05 at 2 37 39 PM

Changes from this PR

Screenshot 2020-07-05 at 2 38 16 PM

### CODE REVIEW

**Comment by sirdarthvader** [comment]
Can someone review this PR

**Comment by sirdarthvader** [comment]
Hey, can someone look into this PR and merge to master or share feedback if otherwise!

**Comment by sirdarthvader** [comment]
Resolved conflicts.

**Comment by gknathk** [comment]
@sirdarthvader, I am trying to test this locally on my machine (Windows 10). I have cloned the react repo and then typed 'npm i && npm start' but it has given me some error as below and the browser loaded the site. However, it looks like some of the elements are not getting loaded properly. Any inputs on what might be missing or what I am missing?

```
>npm i && npm start
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2406 packages in 81.921s

129 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

> covid19india@1.0.0 start C:\Users\gknathk\Documents\GitHub\covid19india-react
> react-scripts start
![covid19_local_screenshot](https://user-images.githubusercontent.com/32987834/89557901-25f48380-d831-11ea-9bba-25b9ff97169b.PNG)



i ｢wds｣: Project is running at http://0.0.0.0:3000/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\gknathk\Documents\GitHub\covid19india-react\public
i ｢wds｣: 404s will fallback to /
Starting the development server...
```

**Comment by sirdarthvader** [comment]
@shuklaayush can you review this and advise if you have any feedback.

**Review by imbudhiraja — APPROVED** [review]

**Comment by sirdarthvader** [comment]
@jeremyphilemon can you take some time and check review this PR.

**Review by sirdarthvader — COMMENTED** [review]
@shuklaayush @imbudhiraja 
I came back to check on the progress of this PR and saw there were some merge conflicts, I have fixed those and updated the PR. 

Also, not sure if @jeremyphilemon is able to take time out of his busy schedule to review the change. However, I see @imbudhiraja has reviewed the changes and approved them, if it's okay, could you please help me getting this to closure.

**Pull request closed without merging**
