### PR TITLE
footer improved

### PR DESCRIPTION
**Pull request by HarshSBhatt**
**Description of PR**

Footer improvement

### CODE REVIEW

**Comment by shuklaayush** [comment]
Hey, I think you can delete the old footer instead of commenting it out. No point in keeping the old code if we merge this

**Comment by strikertanmay** [comment]
@shuklaayush @HarshSBhatt for further changes and improvements in the footer, it would be easy if we make a separate component for the footer. I made this (https://github.com/covid19india/covid19india-react/pull/1005). Please review that PR also.

**Comment by HarshSBhatt** [comment]
> @shuklaayush @HarshSBhatt for further changes and improvements in the footer, it would be easy if we make a separate component for the footer. I made this (#1005). Please review that PR also.

I made a separate component brother

**Comment by JunaidBabu** [comment]
Not working on Firefox with Adblock plus 🤔

**Comment by HarshSBhatt** [comment]
> Not working on Firefox with Adblock plus 🤔

Please explain what is wrong

**Pull request closed without merging**
