### PR TITLE
fix the dropdown UI bug of PR-877

### PR DESCRIPTION
**Pull request by strikertanmay**
**Description of PR**

**Type of PR**

- [x] Bugfix
- [ ] New feature

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

### CODE REVIEW

**Comment by strikertanmay** [comment]
@jeremyphilemon This PR will fix out that thing which I discussed on #877

**Comment by Binu42** [comment]
Hi, @strikertanmay this UI is not good because it's occupying half of the screen for filter in mobile view.
Screenshot from 2020-04-17 23-33-20

**Comment by strikertanmay** [comment]
> Hi, @strikertanmay this UI is not good because it's occupying half of the screen for filter in mobile view.
> Screenshot from 2020-04-17 23-33-20

I checked for different media sizes. No such problem occurs.
If this problem occurs it will easily solve by some increment in top padding for that media size category.

**Comment by strikertanmay** [comment]
@Binu42 
Screenshot from 2020-04-17 23-47-57 (1)
I again checked on google chrome and firefox for the same media size mentioned in SS. No such glitch found.
Which browser u are using ?

**Comment by jeremyphilemon** [comment]
I think what @Binu42 is trying to say is that having the filters arranged as a column is occupying a lot of space of the screen.

Would like to have this filed as issue first so that we can think of a potential solution before creating the PR :)

**Pull request closed without merging**
