### PR TITLE
Cluster tab is now highlighting on active

### PR DESCRIPTION
**Pull request by sirajalam049**
Header cluster tab is now highliting on active

### CODE REVIEW

**Comment by sirajalam049** [comment]
Fixed the issue 
https://github.com/covid19india/covid19india-react/issues/91#issue-587553158

**Comment by shuklaayush** [comment]
Hey @sirajalam049, can you please rebase and push this again? Also, kindly don't add any extra formatting changes. Only code relevant to the issue.

**Comment by sirajalam049** [comment]
@shuklaayush , Sorry for formatting, did in first commit mistakenly, it is not in the second commit. Rebasing and pushing in few minutes.

**Comment by jeremyphilemon** [comment]
Thanks for the PR, this has been patched now! Feel free to open new PRs by looking through accepted issues :)

**Pull request closed without merging**
