### PR TITLE
fixed modal related issues.

### LINKED ISSUE #746: Demographics blocks modal issue
**Describe the bug**
It's an amazing feature though, When we click on any patient ID, the whole website getting stretched, Seems small, But it will better if we fix it :)
**To Reproduce**

1. Go to 'Demographics.'
2. Click on 'Click on Patient ID'
3. Scroll down to 'Observe Blocks and Modal Background'

**Screenshots**
Check the below presentation

ezgif com-video-to-gif

**Desktop (please complete the following information):**

- OS: [Windows 10]
- Browser [All Major Browsers]

**Additional context**
Hope you can sort this out and i suggest you to add feature to close popup by clicking anywhere outside of the modal :) That way we can check them fastly. 

Thanks & Regards,
Vamsi

### PR DESCRIPTION
**Pull request by Binu42**
**Description of PR**
* fixed modal responsive in mobile of width less than 400px. 
* added feature to close modal from outside modal. 
* removed streching of body on modal open.
* fixed a key warning which was happening on console locally.

**Type of PR**

- [x] Bugfix
- [x] New feature

**Relevant Issues**  
Fixes #746 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
#### currently modal is not responsive in small screen :)
before covid19 not responsive in mob
<br>
#### after responsive in small screen
after responsive
<br>

#### other mobile view

other device view

### CODE REVIEW

**Comment by denvamsi** [comment]
Wonderful Patch :)

**Comment by denvamsi** [comment]
A little bit navigation too moves, You can have a look at it :)

**Comment by Binu42** [comment]
> A little bit navigation too moves, You can have a look at it :)

i've done some changes i hope it will solve your this issue.

**Comment by jeremyphilemon** [comment]
Thanks for the PR, really good stuff! :)

**Comment by denvamsi** [comment]
Fantastic job :) and can you please consider some issues on the database page ?

**Comment by Binu42** [comment]
> Fantastic job :) and can you please consider some issues on the database page ?

ya sure

**Pull request merged**
