### PR TITLE
Fix: Made mapstats responsive.

### LINKED ISSUE #951: Homepage is not scaling up properly on mobile
Only the homepage isn't scaling up properly on mobile devices. You can see the extra padding at the right side. I have zoomed and taken the screenshot for better visualization.

Screenshot_2020-04-11-16-44-46-931_com android chrome
** That happened due to the addition of `TESTED` count near map **

### PR DESCRIPTION
**Pull request by jeremyphilemon**
Fixes #951

### CODE REVIEW

**Comment by dpnkrpl** [comment]
gorgeous UI , but menu isn't working. You should have tested this on mobile before deploying. Toggling the menu open a list which is transparent!! A total mess!!

**Comment by Binu42** [comment]
@deep5050 @jeremyphilemon i have fixed it here can you guys look at it once PR #957. link is here https://covid19india-react-25cirxyj3.now.sh/

**Comment by dpnkrpl** [comment]
@Binu42 Yeah, looks great. One suggestion, could you please make the animation a little bit faster? And fix the UI problem on essential page (mobile) i.e. please center align the `feedback` and `add` button??

**Comment by Binu42** [comment]
> @Binu42 Yeah, looks great. One suggestion, could you please make the animation a little bit faster? And fix the UI problem on essential page (mobile) i.e. please center align the `feedback` and `add` button??

ya sure

**Comment by jeremyphilemon** [comment]
@deep5050 Hey thanks for the feedback, we did test on mobiles extensively before rolling out the new navbar. Unfortunately, it looks like the it is being supported by old browsers' webkit.

Could you share details on what phone/browser you were using? 

@Binu42 I'll get back to you wrt your PR :)

**Comment by dpnkrpl** [comment]
@jeremyphilemon I'm on redmi 6 ,latest MIUI 11 , most recent version of chrome. 
Thanks.

**Comment by jeremyphilemon** [comment]
Fixed! Thanks for you feedback boi.

**Comment by Binu42** [comment]
@jeremyphilemon why to let user scroll when navbar is open. this is not expected behaviour, and my PR is solving responsive of homepage and navbar in better way. it will be good if you look at it once.

**Comment by dpnkrpl** [comment]
> @jeremyphilemon why to let user scroll when navbar is open. this is not expected behaviour, and my PR is solving responsive of homepage and navbar in better way. it will be good if you look at it once.

Agreed :)

**Comment by jeremyphilemon** [comment]
@Binu42 hey, I'd really appreciate it if you could open a separate PR that fixes the navbar scroll issue!

**Pull request merged**
