### PR TITLE
Fix: NaN and Infinity in StateMeta Pages

### PR DESCRIPTION
**Pull request by vibvibgyor**
**Description of PR**

Some of the numbers in StateMeta pages were displayed as NaN and Infinity for some of the states. This has been fixed in this PR.

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Before (For Nagaland)
Selection_035

After (For Nagaland)
Selection_036

### CODE REVIEW

**Comment by bee-rickey** [comment]
Lol @jeremyphilemon :P

**Comment by vibvibgyor** [comment]
@jeremyphilemon @bee-rickey @shuklaayush Is something more required from my end here?

**Comment by shuklaayush** [comment]
It seems like the files haven't been linted. The linter would've replaced references to 'var' with 'let'. Also, it would be great if you could reuse the formatNumber( ) method. It should ideally take care of NaN values.

**Comment by vibvibgyor** [comment]
@shuklaayush Actually, I also thought to use this method, but there is no check for _Infinity_ in that function.

Shall I replace all the _var_ with _let_?

**Comment by shuklaayush** [comment]
Just change the format function to check for isFinite() instead of isNaN().

> Shall I replace all the var with let?

Yes, but the linter should automatically do it for you. We only use let or const in the code.

**Comment by vibvibgyor** [comment]
@shuklaayush Thanks, I have added the suggested changes in this commit.

**Comment by vibvibgyor** [comment]
Please let me know, if something more is needed!

**Comment by vibvibgyor** [comment]
@shuklaayush I have few more suggestions for the deep dive charts. Please close/merge this so that I could work further.

**Comment by shuklaayush** [comment]
Hey @vibvibgyor, this seems to have been fixed while refactoring. Thanks for the PR though! :)

**Pull request closed without merging**
