### PR TITLE
Accessibility fixes

### PR DESCRIPTION
**Pull request by abhishekakade**
- Placed `h5.affected-count` outside `table` as it is not a table element. Changed its styles in `App.scss` as needed.
- Added `aria-label` and `alt` on checkbox and icon.

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Thanks for the accessibility patch, could you please squash your commits and rebase?

**Comment by abhishekakade** [comment]
@jeremyphilemon I made a new PR for this so please close this and check #267

**Comment by JunaidBabu** [comment]
Please don't change the formatting. Submit only the files you changed. Please don't change the indentation.

**Comment by JunaidBabu** [comment]
> @jeremyphilemon I made a new PR for this so please close this and check #267

Okay, closing this one.

**Pull request closed without merging**
