### PR TITLE
Improvement in cluster and navbar

### PR DESCRIPTION
**Pull request by sanair96**
- Navbar links now change color on hover
- Open cluster view in iframe so that navigation back is available

covid19trackergif

### CODE REVIEW

**Comment by sanair96** [comment]
Solves some things from issue #15

**Comment by sanair96** [comment]
@jeremyphilemon Can we look at this?

**Comment by jeremyphilemon** [comment]
Looks good! Could you remove the borders though? 

Screen Shot 2020-03-24 at 4 21 27 AM

**Comment by sanair96** [comment]
@jeremyphilemon it has been removed 

Screenshot 2020-03-24 at 10 22 12 AM

**Comment by jeremyphilemon** [comment]
Thanks for the fix!

**Pull request merged**
