### PR TITLE
Fix #469: Added space for district name

### LINKED ISSUE #469: Need some more space for district names
**Describe the bug**
We do not have enough room for district names. Need to increase cell width bit more

**To Reproduce**
Expand any of state to show district details

**Screenshots**
image
**Desktop (please complete the following information):**

- OS: fedora 31
- Browser:  chrome
- Version: 79.0.3945.130

### PR DESCRIPTION
**Pull request by jkandasa**
**Description of PR**
fixes #469

**Type of PR**
- [X ] Bugfix

**Relevant Issues**  
Fixes #469

**Checklist**
- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [ ] Tested on phone

**Screenshots**

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Hey thanks for working on this fix! 

So I've tested it on a mobile screen width and it seems to be working great!
However, on desktops it tends to resize the tables. Could you possibly have that fixed too?




Kapture 2020-04-02 at 5 12 43

**Comment by jkandasa** [comment]
@jeremyphilemon Thanks for the review. Now I have adjusted the colspan of the sub table.
Can you have a look and merge if the fix looks good?

**Review by jeremyphilemon — CHANGES_REQUESTED** [review]
I'm glad your sorted out the resizing issue!

So the width looks too wide right now, and we're also thinking of adding meta data to the right side of the table because there was space. For rows with names like "Mahe" looks suddenly overwhelming to the eyes.

Would it be possible to have the widths of those tables be set to the longest district name of that state?

**Comment by jkandasa** [comment]
@jeremyphilemon Thanks for the review. I do not have enough time to work on this. Hence closing this PR. and the issue.

Thanks for the great work done.

**Pull request closed without merging**
