### PR TITLE
Added "About" in both title bar and Heading

### PR DESCRIPTION
**Pull request by anupamhaldkar**
Replaced "About" with "Faq" as this page shows About section with Question and Answer . 
Also added "About" as  heading in the Top .Earlier It was not there.

**Description of PR**

A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange feedback, and merge!

**Relevant Issues**  
Fixes #...

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**

Add relevant screenshots here

### CODE REVIEW

**Review by anupamhaldkar — COMMENTED** [review]
About fixed

**Review by anupamhaldkar — COMMENTED** [review]
Changed Page title form FAQ to About

**Review by sparsh-99 — COMMENTED** [review]
After deploying, it shows 404-Page Not Found.
Look this out.

**Comment by anupamhaldkar** [comment]
I have built on local server. PageTitle is displaying It works fine, here is attached screenshot 
[
Annotation 2020-06-29 171539
](url)
Annotation 2020-06-29 171402

**Pull request merged**
