### PR TITLE
Date problem in notification fixed.

### LINKED ISSUE #1193: Date problem in notification
Screenshot_20200417-000924

As per screen shot you can notice when i expend notification i show date 17 apr and all the notification of 16th Apr becomes a notification of 17th Apr. 

Above that you display date and time of last notification. 

Notice It with time on screen shot.

### PR DESCRIPTION
**Pull request by shubhamjain2998**
**Description of PR**
Updates in notifications are now displayed datewise.

**Type of PR**

- [x] Bugfix

**Relevant Issues**  
Fixes #1193 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

### loaded more than 5 updates just for testing purpose.

**Screenshots**
Screenshot from 2020-04-17 18-35-40
Screenshot from 2020-04-17 18-35-37

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
Hey, thanks for the PR!

Question: At midnight, the day changes. So would it have the new date showing zero updates, or will it change only if there are new updates on the "current" day?

**Comment by shubhamjain2998** [comment]
@jeremyphilemon currently it will add a new date if the update date is different from the date of fetching it, like this. I have changed the date and time on my laptop but the fetched updates were of one day before. Hope you are clear now :smile:  
Screenshot from 2020-04-18 00-41-11
but I can add zero update thing, as it sounds goods and can be added with 2 3 lines of code.

**Comment by jeremyphilemon** [comment]
I think this will be fine! 

One change though: Instead of showing empty updates on new dates, can you add a message below the new date saying "No updates for today yet", that'll be super useful in understanding the context for empty updates!

Preview: 
Screen Shot 2020-04-17 at 7 15 54 PM

**Comment by shubhamjain2998** [comment]
Done.
Here's the preview
Screenshot from 2020-04-17 22-24-34

**Comment by jeremyphilemon** [comment]
Awesome! Thanks for the PR :)

**Pull request merged**
