### PR TITLE
static analysis testing (lint and format) setup

### LINKED ISSUE #162: Need for static code analysis setup
It is observed that, though eslint config is present in the repo, source code has many lint rule violations. Eg: assignments to variables that are never used, Usage of == instead of === in few places, missing trailing commas, indentation and space issues.

Not having having proper check on these may result in  potential bugs. 

This can be solved by adding few things listed below, 

- prettier setup for code formatting. 
- VS Code recommended extensions file and settings to do format on file save. 
- Pre-commit hook to do lint fix and format fix ( takes care if developers not using VS code as their IDE )
- Lint and prettier Validate npm scripts in package.json ( can be invoked manually OR in CI if required)

### PR DESCRIPTION
**Pull request by vinay-thallam**
fixes #162 

Below items are taken care in this PR.

- Using prettier to take care of code formatting rules and continued to take code quality rules from google's style guideline
- Fixed the existing eslint violations in code
- Added "dbaeumer.vscode-eslint" and "esbenp.prettier-vscode" extensions in vs code recommendations
- Added setting to do format on save of JS and JSON files using prettier
- Added pre-commit hook to do lint fix and format fix. This prevents commit if there exists lint errors in code unless you use --no-verification flag with git commit

Note : Added "validate" script in package.json which can be included in CI pipeline. I have not added it in github workflow file, since I am not sure when to trigger it.

### CODE REVIEW

**Comment by vinay-thallam** [comment]
@jeremyphilemon  @JunaidBabu  Please review

**Comment by jeremyphilemon** [comment]
Hey appreciate the PR! Could you have the formatting the same as what's on master right now, and commit just the configurations? This seems to overwrite most of git history and is harder to track down commits.

Thanks :)

**Comment by jeremyphilemon** [comment]
Hey thank you for this! I know you tried your best to keep the PR updated with the master 😅

I've added the linter configurations myself and also added husky for pre-commit hooks. Thank you anyway :)

**Comment by damnitrahul** [comment]
@vinay-thallam @jeremyphilemon  The prettier styles not getting applied in scss files.
I made a few changes in styles and everything was formatted by prettier.

Please let me know how to enforce styles for scss files? I want to submit a PR.

image

**Pull request closed without merging**
