### PR TITLE
Style: Increase visibility of tooltip in DeepDive

### LINKED ISSUE #1462: Problem in viewing tooltip data in States - Growth Trend - Deep Dive
**Describe the bug**
The data available in the tooltip for States- Growth Trend (Deep-dive section) isn't visible distinctly. It is actually getting merge with a lot of background details. (a big problem for mobile users)

**To Reproduce**

1. Go to "Deep Dive"
2. Scroll down to "Growth trends graph"
3. Click on graph trend, and see the tooltip.

**Expected behavior**
Data should be clearly visible, because if anyone wants to take an insight on a point in the growth trend, then tooltip is the main source of it.

**Screenshots**
Attaching SS from 2 different devices:
Screenshot 1

Screenshot 2

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 80.1

**Smartphone (please complete the following information):**

- Device: Note 8, iphone7
- OS: Android, iOS
- Browser: Chrome
- Version: 80.1

### PR DESCRIPTION
**Pull request by saberprashant**
**Description of PR**
This PR solves the issue when data isn't clearly visible to the user on Growth trends tooltip (deep-dive) section.
Improved the tooltip appearance for Patients by Nationality graph as well (SS attached).

**Type of PR**

- [x] Bugfix

**Relevant Issues**  
fixes #1462 

**Checklist**

- [x] Compiles and passes lint tests
- [x] Properly formatted
- [x] Tested on desktop
- [x] Tested on phone

**Screenshots**
Mobile view:
For Growth Trend graph
Screenshot 1

Desktop view:

For Growth Trend graph
Screenshot 2

For Patients by nationality graph:
Screenshot 3

### CODE REVIEW

**Comment by chatRG** [comment]
Great work.
BTW, any reason why **PATIENTS BY NATIONALITY** tooltip is not changed?

**Comment by saberprashant** [comment]
@chatRG , tooltip for Patients by Nationality isn't causing any problem in viewing the data. That's why I didn't change it. 
But, your point is good. We can make all of them look alike to make the overall UX better.

**Comment by saberprashant** [comment]
I'll make the changes to that as well.

**Comment by saberprashant** [comment]
@jeremyphilemon 
Suggest me if I need to change anything in this PR?
I would be happy to make the required changes.

**Comment by saberprashant** [comment]
@JunaidBabu @shuklaayush @sudevschiz ,
Can anyone of you please check this PR?

**Comment by saberprashant** [comment]
@jeremyphilemon 
Can you please check this one?

**Pull request merged**
